### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by Jammy896** [thesupersonic16/HedgeModManager#111]
HMM Info:
```
    Version: 7.2-4
    Args: 
    StartDir: E:\SteamLibrary\steamapps\Common\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.Combine(String path1, String path2)
       at HedgeModManager.ModInfo.ValidateIncludeDirectories()
       at HedgeModManager.ModsDB.GetInvalidMods()
       at HedgeModManager.MainWindow.RefreshMods()
       at HedgeModManager.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
       at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
       at MS.Internal.LoadedOrUnloadedOperation.DoWork()
       at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
       at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
       at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
       at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
       at System.Windows.Interop.HwndTarget.OnResize()
       at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Please attach the snapshot file that was created when you created this issue.

**Comment by Jammy896** [comment]
![FATAL ERROR](https://user-images.githubusercontent.com/66953390/84684003-ecd61c00-af2f-11ea-87ea-6f6eea4c1902.png)

**Comment by thesupersonic16** [comment]
When you clicked that `Submit Report on GitHub` button, it should open up a file browser with the snapshot. I don't need a screenshot, I need the snapshot file. it's a text file.

**Comment by Jammy896** [comment]
Sorry, hopefully I've do it correctly this time
[HMM_Snapshot_00062020185828.txt](https://github.com/thesupersonic16/HedgeModManager/files/4782062/HMM_Snapshot_00062020185828.txt)

**Comment by Sajidur78** [comment]
I've taken a look at your snapshot file and found out that the `No HUD AT ALL` mod is faulty.

The HMM crash has been fixed on 665feefae13790341aa17112ca5fd36385b062c2 and should be shipped with the next release, for now try this build and see if the issue still occurs.
[HedgeModManager.zip](https://github.com/thesupersonic16/HedgeModManager/files/4783178/HedgeModManager.zip)

**Comment by Jammy896** [comment]
It didn't crash and it works, thanks :D

**Comment by thesupersonic16** [comment]
Looks like we might have forgotten to close this issue. Closing.
