### ISSUE TITLE
[Bug] Failed to Perform Mod Include Checks

### ISSUE THREAD

**Issue by ghost** [thesupersonic16/HedgeModManager#112]
[HMM_Snapshot_00062020124004.txt](https://github.com/thesupersonic16/HedgeModManager/files/4807738/HMM_Snapshot_00062020124004.txt)
HMM Info:
```
    Version: 7.2-4
    Args: 
    StartDir: D:\SteamLibrary\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.Combine(String path1, String path2)
       at HedgeModManager.ModInfo.ValidateIncludeDirectories()
       at HedgeModManager.ModsDB.GetInvalidMods()
       at HedgeModManager.MainWindow.RefreshMods()
       at HedgeModManager.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
       at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
       at MS.Internal.LoadedOrUnloadedOperation.DoWork()
       at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
       at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
       at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
       at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
       at System.Windows.Interop.HwndTarget.OnResize()
       at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Thanks for sending your snapshot file. I have taken a look and I have identified the mod `EmpireCity Pack` has a malformed INI file. 

This issue has already been reported and fixed in #111 and will be available in the next HedgeModManager update.

For the time being you can do one of either the options:
**1. Update to a patched version (RECOMMENDED)**
Below is a build of HedgeModManager 7.2-4 which also contains the fix for this issue. Just download it and install it over the current versions of HedgeModManager you currently have.

[Download HedgeModManager.zip](https://github.com/thesupersonic16/HedgeModManager/files/4783178/HedgeModManager.zip)

___
**2. Manually fix the mod (Only if you don't want to update)**
To do this you will need to locate the `EmpireCityPack` folder from your Mods folder, and open the `mod.ini` file with any text editor. On the second(2nd) line which says `IncludeDir0="."/mods/EmpireCityPack"`, change that to `IncludeDir0="."`
This will fix the error in the INI and should allow HedgeModManager to load the data correctly.
