### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by SonicFan345** [thesupersonic16/HedgeModManager#114]
HMM Info:
```
    Version: 7.2-4
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: TypeLoadException
    Message: Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
    Source: HedgeModManager
    Function: Void CheckCodeCompatibility()
    StackTrace: 
       at HedgeModManager.MainWindow.CheckCodeCompatibility()
       at HedgeModManager.MainWindow.RefreshMods()
       at HedgeModManager.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at MS.Internal.FrameworkObject.OnLoaded(RoutedEventArgs args)
       at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
       at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
       at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
       at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
       at System.Windows.Media.MediaContext.RenderMessageHandl

**Comment by Sajidur78** [comment]
Update .Net Framework

**Comment by thesupersonic16** [comment]
Also make sure you are on Windows 8.1 or Windows 10.

**Comment by thesupersonic16** [comment]
Closing due to inactivity. If the issue still occurs on the latest version please reopen this issue.
