### ISSUE TITLE
HedgeModManager

### ISSUE THREAD

**Issue by Veitaserum4** [thesupersonic16/HedgeModManager#119]
[HMM_Snapshot_00072020140341.txt](https://github.com/thesupersonic16/HedgeModManager/files/4920430/HMM_Snapshot_00072020140341.txt)
HMM Info:
```
    Version: 7.2-5
    Args: 
    StartDir: C:\Users\nashk_vcsfjmp\OneDrive\Desktop\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: UnauthorizedAccessException
    Message: Access to the path 'C:\Users\nashk_vcsfjmp\AppData\Local\Temp\tmpFE81.tmp' is denied.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.File.InternalDelete(String path, Boolean checkHost)
       at HedgeModManager.HedgeApp.GetCPKREDIRFileVersion(Nullable`1 packed)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by Veitaserum4** [comment]
I can't open it because it keeps on coming up with the same error

**Comment by Sajidur78** [comment]
Try running as administrator

**Comment by Veitaserum4** [comment]
mk

**Comment by Veitaserum4** [comment]
its no use

**Comment by Veitaserum4** [comment]
well now it just randomly decided to work



thanks i guess
