### ISSUE TITLE
[Bug] HedgeModManager Crash UnauthorizedAccessException

### ISSUE THREAD

**Issue by DARKTHEHEDGEHOG** [thesupersonic16/HedgeModManager#121]
HMM Info:
```
Version: 7.2-5
Args:
StartDir: C:\Users\junio\Desktop\Games\Sonic Generations\
Process Level: Administrator
Game: Sonic Generations
SteamGame: Sonic Generations
```
Exception: 
```
Type: UnauthorizedAccessException
Message: Access to the path 'C:\Users\junio\Desktop\Games\Sonic Generations\SonicGenerations.exe.bak' is denied.
Source: mscorlib
Function: Void WinIOError(Int32, System.String)
StackTrace: at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at
System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost) at
HedgeModManager.HedgeApp.InstallCPKREDIR(String executablePath, Nullable`1 install) at
HedgeModManager.HedgeApp.Main(String[] args)
```

**Comment by thesupersonic16** [comment]
Btw I know this is your first issue, but the crash report doesn't go in the title field, it goes in the description. And it seems its another CPKREDIR unpatch error.

Currently we are unsure what exactly happened, but in your Generations folder, just delete the SonicGenerations.exe.bak file or rename it to something else as its failing to make a backup.

Also I heavily discourage moving Steam games outside of your Steam Library.

**Comment by DARKTHEHEDGEHOG** [comment]
is now giving this error HMM Info:
``
    Version: 7.2-5
    Args:
    StartDir: C: \ Users \ junio \ Desktop \ Games \ Sonic Generations \
    Process Level: Administrator
    Game: Sonic Generations
    SteamGame: Sonic Generations
``

Exception:
``
    Type: UnauthorizedAccessException
    Message: Access to the path 'C: \ Users \ junio \ Desktop \ Games \ Sonic Generations \ SonicGenerations.exe' is denied.
    Source: mscorlib
    Function: Void WinIOError (Int32, System.String)
    StackTrace:
       at System.IO .__ Error.WinIOError (Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init (String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor (String path, FileMode mode, FileAccess access, FileShare share)
       at HedgeModManager.HedgeApp.InstallCPKREDIR (String executablePath, Nullable`1 install)
       at HedgeModManager.HedgeApp.Main (String [] args)
    InnerException:
``

HMM Info:
``
    Version: 7.2-5
    Args:
    StartDir: C: \ Users \ junio \ Desktop \ Games \ Sonic Generations \
    Process Level: Administrator
    Game: Sonic Generations
    SteamGame: Sonic Generations
``

Exception:
``
    Type: UnauthorizedAccessException
    Message: Access to the path 'C: \ Users \ junio \ Desktop \ Games \ Sonic Generations \ SonicGenerations.exe' is denied.
    Source: mscorlib
    Function: Void WinIOError (Int32, System.String)
    StackTrace:
       at System.IO .__ Error.WinIOError (Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init (String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor (String path, FileMode mode, FileAccess access, FileShare share)
       at HedgeModManager.HedgeApp.InstallCPKREDIR (String executablePath, Nullable`1 install)
       at HedgeModManager.HedgeApp.Main (String [] args)
    InnerException:
``

**Comment by DARKTHEHEDGEHOG** [comment]
is now giving this error HMM Info:
```
    Version: 7.2-5
    Args: 
    StartDir: C:\Users\junio\Desktop\Games\Sonic Generations\
    Process Level: Administrator
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: UnauthorizedAccessException
    Message: Access to the path 'C:\Users\junio\Desktop\Games\Sonic Generations\SonicGenerations.exe.bak' is denied.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
       at HedgeModManager.HedgeApp.InstallCPKREDIR(String executablePath, Nullable`1 install)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```


``

**Comment by DARKTHEHEDGEHOG** [comment]
and when I open the hedge it appears again

**Comment by DARKTHEHEDGEHOG** [comment]
help me please

**Comment by DARKTHEHEDGEHOG** [comment]
give me a rar of downlaod so that fixed please

**Comment by thesupersonic16** [comment]
Can you please stop constantly posting replies like that? Also here is a build of the newest commit. Try this.

[HedgeModManager.zip](https://github.com/thesupersonic16/HedgeModManager/files/4966553/HedgeModManager.zip)

**Comment by RagdollClash** [comment]
Please stop creating the same issues over and over again.

**Comment by thesupersonic16** [comment]
As a note to this issue closure, we do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam.
