### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by Cosmiz** [thesupersonic16/HedgeModManager#127]
HMM Info:
```
    Version: 7.2-5
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: IOException
    Message: The process cannot access the file 'C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\cpkredir.ini' because it is being used by another process.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.CPKREDIRConfig.Save(String path)
       at HedgeModManager.MainWindow.<SaveModsDB>d__14.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<<UI_SaveAndPlay_Click>b__27_0>d.MoveNext()
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Are you able to reproduce this same issue consistently? We need you tell us what you did that made this error occur.

**Comment by thesupersonic16** [comment]
Closing due to inactivity. If the issue still occurs on the latest version please reopen this issue.
