### ISSUE TITLE
[Sonic Lost World] 

### ISSUE THREAD

**Issue by pico1021** [thesupersonic16/HedgeModManager#133]
[HMM_Snapshot_00082020220757.txt](https://github.com/thesupersonic16/HedgeModManager/files/5106386/HMM_Snapshot_00082020220757.txt)
HMM Info:
```
    Version: 7.2-5
    Args: 
    StartDir: T:\SteamLibrary\steamapps\common\Sonic Lost World
    Process Level: User
    Game: Sonic Lost World
    SteamGame: Sonic Lost World
```

Exception:
```
    Type: InvalidOperationException
    Message: The calling thread cannot access this object because a different thread owns it.
    Source: WindowsBase
    Function: Void VerifyAccess()
    StackTrace: 
       at System.Windows.Threading.Dispatcher.VerifyAccess()
       at System.Windows.Application.CriticalShutdown(Int32 exitCode)
       at HedgeModManager.MainWindow.StartGame()
       at HedgeModManager.MainWindow.<<UI_SaveAndPlay_Click>b__27_0>d.MoveNext()
    InnerException: 
```

**Comment by RagdollClash** [comment]
Please don't make duplicate issues. Closing in favor of #132.
