### ISSUE TITLE
I can't play Sonic Generations

### ISSUE THREAD

**Issue by andres090707** [thesupersonic16/HedgeModManager#135]
![dadadaddada](https://user-images.githubusercontent.com/70530744/91738015-81d2d380-eb75-11ea-9da2-761a16430233.JPG)

This happens when I open Sonic Generations.

**Comment by thesupersonic16** [comment]
Do you have any mods enabled? Also what happens when you press the OK button?

**Comment by andres090707** [comment]
![dsadsdsadsdsdsadas](https://user-images.githubusercontent.com/70530744/91739363-6b2d7c00-eb77-11ea-813f-675f9a6f8aa0.JPG)
I have this mods

**Comment by andres090707** [comment]
When I press the OK button the game closes.

**Comment by thesupersonic16** [comment]
Does the same happen with no mods selected?

**Comment by andres090707** [comment]
Yes

**Comment by thesupersonic16** [comment]
Are you running the legit Steam version of the game? and does this only happen with the modloader installed?

**Comment by andres090707** [comment]
Im running the Steam version of the game, It happens with the modloader and the Steam version

**Comment by thesupersonic16** [comment]
The game works fine when you uninstall the modloader, right? I just need to know if its the game or the modloader that's having issues.

**Comment by andres090707** [comment]
The game works fine with no mod loader, I uninstalled the mod loader.

**Comment by thesupersonic16** [comment]
Can you install the modloader and in the Settings enable the option `Enable debug console`. This should make a console window show up, and if you can copy everything in it and upload it as a .txt file here. This is so I can get an idea whats going.

**Comment by andres090707** [comment]
his is:   D:\SteamLibrary\steamapps\common\Sonic Generations\cpkredir.dll v0.5.0.8
Loaded by: D:\SteamLibrary\steamapps\common\Sonic Generations\SonicGenerations.exe v1.0.0.5
Time:      2020-08-31 11:05:24.543
; .text    : VS=00FC0C3D VA=00401000 RS=00FC0E00 C=60000020
; PSFD00   : VS=00001D78 VA=013C2000 RS=00001E00 C=60000020
; .rdata   : VS=0043EBD2 VA=013C4000 RS=0043EC00 C=40000040
; .data    : VS=008A06FC VA=01803000 RS=00320000 C=C0000040
; .tls     : VS=00000049 VA=020A4000 RS=00000200 C=C0000040
; .rsrc    : VS=00005940 VA=020A5000 RS=00005A00 C=40000040
Config: PlaceTocAtEnd=True
Config: HandleCpksWithoutExtFiles=False
Config: ReadBlockSize=4096
Config: ModsDatabase=D:\SteamLibrary\steamapps\common\Sonic Generations\mods\ModsDB.ini
Config: EnableSaveFileRedirection=False
Config: SaveFileReadThrough=True
Config: SaveFileFallback=D:\SteamLibrary\steamapps\common\Sonic Generations\cpkredir.sav
Config: SaveFileOverride=
Detected CRI module strings:
ADXDSOUND8/PCx86             Ver.1.04     Build:Apr  8 2010 14:18:14  MSC1500,MT
CRI ERR/PCx86                Ver.1.01     Build:Apr  8 2010 14:18:05  MSC1500,MT
SVM/PCx86                    Ver.1.68     Build:Apr  8 2010 14:18:00  MSC1500,MT
XECI/PCx86                   Ver.1.84     Build:Apr  8 2010 14:18:00  MSC1500,MT
CVFS/PCx86                   Ver.2.60     Build:Apr  8 2010 14:18:05
MFCI/PCx86                   Ver.1.24     Build:Apr  8 2010 14:18:02  MSC1500,MT
ADXPC(PRO)                   Ver.1.76     Build:Apr  8 2010 14:18:12
ADXDS                        Ver.0900     Build:Apr  8 2010 14:18:12
ADXT/PCx86                   Ver.11.05    Build:Apr  8 2010 14:18:13  MSC1500,MT
MCRNA                        Ver.2.06     Build:Apr  8 2010 14:18:02
CRI CRW:WIN/PCx86            Ver.0.83     Build:Apr  8 2010 14:18:06  MSC1500,MT
CRI CRS/PCx86                Ver.1.03     Build:Apr  8 2010 14:18:06  MSC1500,MT
CRI DLG/PCx86                Ver.1.15     Build:Apr  8 2010 14:18:05  MSC1500,MT
LSC/PCx86                    Ver.2.32     Build:Apr  8 2010 14:18:04  MSC1500,MT
ADXF/PCx86                   Ver.7.74     Build:Apr  8 2010 14:18:15  MSC1500,MT
SJ/PCx86                     Ver.6.47     Build:Apr  8 2010 14:18:01  MSC1500,MT
SKG/PCx86                    Ver.1.01     Build:Apr  8 2010 14:18:14  MSC1500,MT
AFAnalyzer/PCx86             Ver.1.00     Build:Apr  8 2010 14:17:59  MSC1500,MT
CRI Audio/PCx86              Ver.3.57.06  Build:Apr  1 2011 21:56:22  MSC1500,MT,for CriFs2
CRI Sound Renderer/PCx86     Ver.1.05.00  Build:Apr  1 2011 21:56:15  MSC1500,MT
CRI AHX (CPP)/PCx86          Ver.1.90     Build:Apr  1 2011 21:56:23  MSC1500,MT
CRI Error/PCx86              Ver.1.03.00  Build:Apr  1 2011 21:08:23  MSC1500,MT
CRI Heap/PCx86               Ver.1.21.02  Build:Apr  1 2011 21:08:22  MSC1500,MT
CRI Critical Section/PCx86   Ver.1.00.12  Build:Apr  1 2011 21:08:21  MSC1500,MT
CRI C Runtime Wrapper/PCx86  Ver.1.02.00  Build:Apr  1 2011 21:08:23  MSC1500,MT
CRI Stream Joint/PCx86       Ver.1.01.00  Build:Apr  1 2011 21:08:21  MSC1500,MT
CRI ADX Decoder/PCx86        Ver.1.00.08  Build:Apr  1 2011 21:08:22  MSC1500,MT
HCA Decoder (Float)          Ver.1.40     Build:Apr  1 2011 21:08:23
CRI Base/PCx86               Ver.2.15.01  Build:Apr  1 2011 21:08:23  MSC1500,MT
CRI Thread/PCx86             Ver.1.01.01  Build:Apr  1 2011 21:08:22  MSC1500,MT
CRI UTF Retriever/PCx86      Ver.1.00.01  Build:Apr  1 2011 21:08:22  MSC1500,MT
CRI File System/PCx86        Ver.2.24.04  Build:Apr  1 2011 21:08:31  MSC1500,MT
CriFsBinder/PCx86            Ver.1.02.63  Build:Apr  1 2011 21:08:31  MSC1500,MT
CriFsGroupLoader/PCx86       Ver.1.00.73  Build:Apr  1 2011 21:08:31  MSC1500,MT
CRI CPK Analyzer/PCx86       Ver.0.99.32  Build:Apr  1 2011 21:08:31  MSC1500,MT
MWSFD/PCx86                  Ver.5.00     Build:Apr 12 2010 13:11:28  MSC1500,MT
CRI SFD/PCx86                Ver.2.129    Build:Apr 12 2010 13:10:26  MSC1500,MT
CRI ASVD/PCx86               Ver.0.14     Build:Apr 12 2010 13:11:45  MSC1500,MT
CRI SFH/PCx86                Ver.2.25     Build:Apr 12 2010 13:08:44  MSC1500,MT
CRI SUD/PCx86                Ver.0.05     Build:Apr 12 2010 13:09:33
CRI SFX/PCx86                Ver.2.49     Build:Apr 12 2010 13:09:50
CRI MPS/PCx86                Ver.2.068    Build:Apr 12 2010 13:07:56  MSC1500,MT
CRI MPV/PCx86                Ver.2.067    Build:Apr 12 2010 13:08:18  MSC1500,MT
CRI FNO/PCx86                Ver.1.001    Build:Apr 12 2010 13:12:45  MSC1500,MT
CRI M2TSD/PCx86              Ver.2.066    Build:Apr 12 2010 13:08:28  MSC1500,MT
CRI M2PES/PCx86              Ver.2.066    Build:Apr 12 2010 13:08:29  MSC1500,MT
CRI M2T/PCx86                Ver.2.066    Build:Apr 12 2010 13:08:28  MSC1500,MT
CRI CFT/PCx86                Ver.2.17     Build:Apr 12 2010 13:09:45  MSC1500,MT
CRI DCT/PCx86                Ver.2.037    Build:Apr 12 2010 13:08:38  MSC1500,MT
AIXP/PCx86                   Ver.3.20     Build:Apr  8 2010 14:18:08  MSC1500,MT
CRI CFG/PCx86                Ver.1.03     Build:Apr  8 2010 14:18:06  MSC1500,MT
MPASJD/PCx86                 Ver.1.51     Build:Apr  8 2010 14:18:02  MSC1500,MT
M2ASJD/PCx86                 Ver.1.32     Build:Apr  8 2010 14:18:03  MSC1500,MT
LPCMSJD/PCx86                Ver.1.00     Build:Apr  8 2010 14:18:05  MSC1500,MT
HEAPMNG/PCx86                Ver.0.92     Build:Apr  8 2010 14:18:05  MSC1500,MT
CRI Handle Manager/PCx86     Ver.1.00.07  Build:Apr  1 2011 21:08:23  MSC1500,MT
CRI LLDECOMP3/PCx86          Ver.0.90.04  Build:Apr  1 2011 21:08:22  MSC1500,MT
CRI Timer/PCx86              Ver.0.50.02  Build:Apr  1 2011 21:08:21  MSC1500,MT
Successfully installed custom CriFsIo methods!
Setting breakpad minidump AppID = 71340

**Comment by thesupersonic16** [comment]
In the mods folder, can you delete the file `Codes.dll` and in HMM Press "Play" **NOT** "Save" or "Save and Play".

This is to disable code loading so we can narrow down the issue.

**Comment by andres090707** [comment]
Still happening

**Comment by andres090707** [comment]
Somethig changed



This is:   D:\SteamLibrary\steamapps\common\Sonic Generations\cpkredir.dll v0.5.0.8
Loaded by: D:\SteamLibrary\steamapps\common\Sonic Generations\SonicGenerations.exe v1.0.0.5
Time:      2020-08-31 11:16:32.039
; .text    : VS=00FC0C3D VA=00401000 RS=00FC0E00 C=60000020
; PSFD00   : VS=00001D78 VA=013C2000 RS=00001E00 C=60000020
; .rdata   : VS=0043EBD2 VA=013C4000 RS=0043EC00 C=40000040
; .data    : VS=008A06FC VA=01803000 RS=00320000 C=C0000040
; .tls     : VS=00000049 VA=020A4000 RS=00000200 C=C0000040
; .rsrc    : VS=00005940 VA=020A5000 RS=00005A00 C=40000040
Config: PlaceTocAtEnd=True
Config: HandleCpksWithoutExtFiles=False
Config: ReadBlockSize=4096
Config: ModsDatabase=D:\SteamLibrary\steamapps\common\Sonic Generations\mods\ModsDB.ini
Config: EnableSaveFileRedirection=False
Config: SaveFileReadThrough=True
Config: SaveFileFallback=D:\SteamLibrary\steamapps\common\Sonic Generations\cpkredir.sav
Config: SaveFileOverride=
Detected CRI module strings:
ADXDSOUND8/PCx86             Ver.1.04     Build:Apr  8 2010 14:18:14  MSC1500,MT
CRI ERR/PCx86                Ver.1.01     Build:Apr  8 2010 14:18:05  MSC1500,MT
SVM/PCx86                    Ver.1.68     Build:Apr  8 2010 14:18:00  MSC1500,MT
XECI/PCx86                   Ver.1.84     Build:Apr  8 2010 14:18:00  MSC1500,MT
CVFS/PCx86                   Ver.2.60     Build:Apr  8 2010 14:18:05
MFCI/PCx86                   Ver.1.24     Build:Apr  8 2010 14:18:02  MSC1500,MT
ADXPC(PRO)                   Ver.1.76     Build:Apr  8 2010 14:18:12
ADXDS                        Ver.0900     Build:Apr  8 2010 14:18:12
ADXT/PCx86                   Ver.11.05    Build:Apr  8 2010 14:18:13  MSC1500,MT
MCRNA                        Ver.2.06     Build:Apr  8 2010 14:18:02
CRI CRW:WIN/PCx86            Ver.0.83     Build:Apr  8 2010 14:18:06  MSC1500,MT
CRI CRS/PCx86                Ver.1.03     Build:Apr  8 2010 14:18:06  MSC1500,MT
CRI DLG/PCx86                Ver.1.15     Build:Apr  8 2010 14:18:05  MSC1500,MT
LSC/PCx86                    Ver.2.32     Build:Apr  8 2010 14:18:04  MSC1500,MT
ADXF/PCx86                   Ver.7.74     Build:Apr  8 2010 14:18:15  MSC1500,MT
SJ/PCx86                     Ver.6.47     Build:Apr  8 2010 14:18:01  MSC1500,MT
SKG/PCx86                    Ver.1.01     Build:Apr  8 2010 14:18:14  MSC1500,MT
AFAnalyzer/PCx86             Ver.1.00     Build:Apr  8 2010 14:17:59  MSC1500,MT
CRI Audio/PCx86              Ver.3.57.06  Build:Apr  1 2011 21:56:22  MSC1500,MT,for CriFs2
CRI Sound Renderer/PCx86     Ver.1.05.00  Build:Apr  1 2011 21:56:15  MSC1500,MT
CRI AHX (CPP)/PCx86          Ver.1.90     Build:Apr  1 2011 21:56:23  MSC1500,MT
CRI Error/PCx86              Ver.1.03.00  Build:Apr  1 2011 21:08:23  MSC1500,MT
CRI Heap/PCx86               Ver.1.21.02  Build:Apr  1 2011 21:08:22  MSC1500,MT
CRI Critical Section/PCx86   Ver.1.00.12  Build:Apr  1 2011 21:08:21  MSC1500,MT
CRI C Runtime Wrapper/PCx86  Ver.1.02.00  Build:Apr  1 2011 21:08:23  MSC1500,MT
CRI Stream Joint/PCx86       Ver.1.01.00  Build:Apr  1 2011 21:08:21  MSC1500,MT
CRI ADX Decoder/PCx86        Ver.1.00.08  Build:Apr  1 2011 21:08:22  MSC1500,MT
HCA Decoder (Float)          Ver.1.40     Build:Apr  1 2011 21:08:23
CRI Base/PCx86               Ver.2.15.01  Build:Apr  1 2011 21:08:23  MSC1500,MT
CRI Thread/PCx86             Ver.1.01.01  Build:Apr  1 2011 21:08:22  MSC1500,MT
CRI UTF Retriever/PCx86      Ver.1.00.01  Build:Apr  1 2011 21:08:22  MSC1500,MT
CRI File System/PCx86        Ver.2.24.04  Build:Apr  1 2011 21:08:31  MSC1500,MT
CriFsBinder/PCx86            Ver.1.02.63  Build:Apr  1 2011 21:08:31  MSC1500,MT
CriFsGroupLoader/PCx86       Ver.1.00.73  Build:Apr  1 2011 21:08:31  MSC1500,MT
CRI CPK Analyzer/PCx86       Ver.0.99.32  Build:Apr  1 2011 21:08:31  MSC1500,MT
MWSFD/PCx86                  Ver.5.00     Build:Apr 12 2010 13:11:28  MSC1500,MT
CRI SFD/PCx86                Ver.2.129    Build:Apr 12 2010 13:10:26  MSC1500,MT
CRI ASVD/PCx86               Ver.0.14     Build:Apr 12 2010 13:11:45  MSC1500,MT
CRI SFH/PCx86                Ver.2.25     Build:Apr 12 2010 13:08:44  MSC1500,MT
CRI SUD/PCx86                Ver.0.05     Build:Apr 12 2010 13:09:33
CRI SFX/PCx86                Ver.2.49     Build:Apr 12 2010 13:09:50
CRI MPS/PCx86                Ver.2.068    Build:Apr 12 2010 13:07:56  MSC1500,MT
CRI MPV/PCx86                Ver.2.067    Build:Apr 12 2010 13:08:18  MSC1500,MT
CRI FNO/PCx86                Ver.1.001    Build:Apr 12 2010 13:12:45  MSC1500,MT
CRI M2TSD/PCx86              Ver.2.066    Build:Apr 12 2010 13:08:28  MSC1500,MT
CRI M2PES/PCx86              Ver.2.066    Build:Apr 12 2010 13:08:29  MSC1500,MT
CRI M2T/PCx86                Ver.2.066    Build:Apr 12 2010 13:08:28  MSC1500,MT
CRI CFT/PCx86                Ver.2.17     Build:Apr 12 2010 13:09:45  MSC1500,MT
CRI DCT/PCx86                Ver.2.037    Build:Apr 12 2010 13:08:38  MSC1500,MT
AIXP/PCx86                   Ver.3.20     Build:Apr  8 2010 14:18:08  MSC1500,MT
CRI CFG/PCx86                Ver.1.03     Build:Apr  8 2010 14:18:06  MSC1500,MT
MPASJD/PCx86                 Ver.1.51     Build:Apr  8 2010 14:18:02  MSC1500,MT
M2ASJD/PCx86                 Ver.1.32     Build:Apr  8 2010 14:18:03  MSC1500,MT
LPCMSJD/PCx86                Ver.1.00     Build:Apr  8 2010 14:18:05  MSC1500,MT
HEAPMNG/PCx86                Ver.0.92     Build:Apr  8 2010 14:18:05  MSC1500,MT
CRI Handle Manager/PCx86     Ver.1.00.07  Build:Apr  1 2011 21:08:23  MSC1500,MT
CRI LLDECOMP3/PCx86          Ver.0.90.04  Build:Apr  1 2011 21:08:22  MSC1500,MT
CRI Timer/PCx86              Ver.0.50.02  Build:Apr  1 2011 21:08:21  MSC1500,MT
Successfully installed custom CriFsIo methods!
OPEN:  "disk\bb3.cpk" o=FILE_MODE_OPEN a=FILE_ACCESS_READ
Analyzing CPK file "disk\bb3.cpk"
no external files
Not handling file "disk\bb3.cpk"
OPEN:  handle=$620, result=0
OPEN:  "disk\bb3.cpk" o=FILE_MODE_OPEN a=FILE_ACCESS_READ
Analyzing CPK file "disk\bb3.cpk"
no external files
Not handling file "disk\bb3.cpk"
OPEN:  handle=$620, result=0

**Comment by thesupersonic16** [comment]
Can you try disable all the mods then try "Save and Play"? No need to send the console info now.

**Comment by andres090707** [comment]
Ok

**Comment by andres090707** [comment]
Still happenig  :(

**Comment by thesupersonic16** [comment]
Did Generations work after you first installed HMM?

**Comment by andres090707** [comment]
Yes

**Comment by thesupersonic16** [comment]
Could be possible a mod you recently installed might have caused an issue. Can you try rename the `mods` folder to something else? So HMM will start up clean with no mods installed.

**Comment by andres090707** [comment]
Oh no

**Comment by andres090707** [comment]
HMM Info:
    Version: 7.2-6
    Args: 
    StartDir: D:\SteamLibrary\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations

Exception:
    Type: DirectoryNotFoundException
    Message: Could not find a part of the path 'D:\SteamLibrary\steamapps\common\Sonic Generations\mods'.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileSystemEnumerableIterator`1.CommonInit()
       at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
       at System.IO.Directory.GetDirectories(String path)
       at HedgeModManager.ModsDB.DetectMods()
       at HedgeModManager.MainWindow.RefreshMods()
       at HedgeModManager.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
       at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
       at MS.Internal.LoadedOrUnloadedOperation.DoWork()
       at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
       at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
       at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
       at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
       at System.Windows.Interop.HwndTarget.OnResize()
       at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
    InnerException:

**Comment by thesupersonic16** [comment]
I might take a look at that error later. Just make a new folder called `mods` and start HMM.
After that make sure the modloader is installed and click `Save and Play` with no mods installed.

**Comment by andres090707** [comment]
Still happening

**Comment by thesupersonic16** [comment]
Maybe try closing HMM, delete cpkredir.ini then open HMM again.

**Comment by andres090707** [comment]
![image](https://user-images.githubusercontent.com/70530744/91750116-2a8a2e80-eb88-11ea-8379-cd040687db38.png)
All I found was this

**Comment by thesupersonic16** [comment]
The one below the `cpkredir.dll` is what you need to delete.

**Comment by andres090707** [comment]
Nothing changed

**Comment by thesupersonic16** [comment]
I think I'm going to get the author of the modloader to handle this issue, I have tried everything I could think of to troubleshoot this issue.

**Comment by andres090707** [comment]
Ok

**Comment by Sajidur78** [comment]
This is a weird issue. 
@andres090707 Can you try changing your system language and see if the contents of the message box change? And can you check `%localappdata%/crashdumps` for any dumps with SonicGenerations in the name?

**Comment by andres090707** [comment]
Ok

**Comment by thesupersonic16** [comment]
Closing due to inactivity. If the issue still occurs on the latest version please reopen this issue.
