### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by Luigi107-png** [thesupersonic16/HedgeModManager#141]
HMM Info:
```
    Version: 7.2-4
    Args: 
    StartDir: C:\Program Files\SEGA\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: UnauthorizedAccessException
    Message: Access to the path 'C:\Program Files\SEGA\Sonic Generations\cpkredir.dll' is denied.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
       at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
       at HedgeModManager.App.Main(String[] args)
    InnerException: 
```

**Comment by thesupersonic16** [comment]
This issue has already been fixed in newer versions of HedgeModManager, please update the manager manually.

Also HedgeModManager only supports the Steam version of Sonic Generations.
