### ISSUE TITLE
[Sonic Generations] I've gotten this multiple times on startup. What is going wrong?

### ISSUE THREAD

**Issue by It-NightWolf-Ye** [thesupersonic16/HedgeModManager#150]
HMM Info:
```
    Version: 7.2-6
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: TypeLoadException
    Message: Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
    Source: HedgeModManager
    Function: Void CheckCodeCompatibility()
    StackTrace: 
       at HedgeModManager.MainWindow.CheckCodeCompatibility()
       at HedgeModManager.MainWindow.RefreshMods()
       at HedgeModManager.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
       at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
       at MS.Internal.LoadedOrUnloadedOperation.DoWork()
       at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
       at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
       at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Objec

**Comment by thesupersonic16** [comment]
You might be running an out of date version of .NET Framework. Try updating it.

[.NET Framework 4.8 Installer](https://go.microsoft.com/fwlink/?linkid=2088631)

**Comment by It-NightWolf-Ye** [comment]
Problem.

I'm stuck, as that's supposedly not supported on my OS (Windows 8)

**Comment by thesupersonic16** [comment]
You need to upgrade to Windows 8.1 or Windows 10.

**Comment by It-NightWolf-Ye** [comment]
[insert swear word here].

**Comment by thesupersonic16** [comment]
Closing due to inactivity.
