### ISSUE TITLE
[Sonic Forces] 

### ISSUE THREAD

**Issue by enrique20002021** [thesupersonic16/HedgeModManager#154]
HMM Info:
```
    Version: 7.2-7
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicForces\build\main\projects\exec
    Process Level: Administrator
    Game: Sonic Forces
    SteamGame: Sonic Forces
```

Exception:
```
    Type: Exception
    Message: Error compiling codes
(35,16): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
(38,16): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
(41,16): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
(47,16): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
(50,16): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
(56,16): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
(106,16): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'

    Source: HedgeModManager
    Function: System.Threading.Tasks.Task CompileCodes(System.Collections.Generic.IEnumerable`1[HedgeModManager.Code], System.IO.Stream, System.String[])
    StackTrace: 
       at HedgeModManager.CodeProvider.CompileCodes(IEnumerable`1 sources, Stream resultStream, String[] loadPaths)
       at HedgeModManager.CodeProvider.CompileCodes(IEnumerable`1 sources, String assemblyPath, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__20.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__14.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<>c__DisplayClass29_0.<<UI_SaveAndPlay_Click>b__0>d.MoveNext()
    InnerException: 
```

**Comment by enrique20002021** [comment]
Any solution?

**Comment by Sajidur78** [comment]
What OS are you running? And what version of .net framework do you have installed?

**Comment by enrique20002021** [comment]
Estoy en windows10 *64 y la net framework 4.8 avances services

**Comment by enrique20002021** [comment]
Sabrías solucionarlo, hace como que se abre pero se cierra automáticamente Sonic forces.exe o algo así

**Comment by enrique20002021** [comment]
Una cosa muy rara.

**Comment by thesupersonic16** [comment]
Please speak only in English. We can not help resolve your issue if you do not speak a language we understand.

**Comment by enrique20002021** [comment]
I'm in 10*64 S.O and the net framework that i hace installed os 4.8 avances services

**Comment by enrique20002021** [comment]
It seems open but the .exe (Sonic forces) closes inmediatly

**Comment by enrique20002021** [comment]
My net framework is 4.8

**Comment by enrique20002021** [comment]
Please Any solution?

**Comment by Sajidur78** [comment]
Try re-installing .net framework.

**Comment by thesupersonic16** [comment]
Closing due to inactivity.
