### ISSUE TITLE
[Sonic Forces] Can't download mod

### ISSUE THREAD

**Issue by Bricksider** [thesupersonic16/HedgeModManager#160]
HMM Info:
```
    Version: 7.2-6
    Args: -gb hedgemmforces:https://gamebanana.com/mmdl/368837,Skin,159865
    StartDir: D:\games\Steam Games\steamapps\common\SonicForces\build\main\projects\exec
    Process Level: User
    Game: Sonic Forces
    SteamGame: Sonic Forces
```

Exception:
```
    Type: WebException
    Message: The remote server returned an error: (404) Not Found.
    Source: System
    Function: System.Net.WebResponse GetResponse()
    StackTrace: 
       at System.Net.HttpWebRequest.GetResponse()
       at HedgeModManager.UI.GBModWindow.Download_Click(Object sender, RoutedEventArgs e)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.Controls.Primitives.ButtonBase.OnClick()
       at System.Windows.Controls.Button.OnClick()
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Window.ShowHelper(Object booleanBox)
       at System.Windows.Window.ShowDialog()
       at GameBananaAPI.GBAPI.ParseCommandLine(String line)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by Bricksider** [comment]
I can't download "Curved female body" mod and a lot of other mods that is mostly old (more than year), and freecam mod

**Comment by thesupersonic16** [comment]
Not really an issue with HedgeModManager. GameBanana is currently experiencing an outage.

**Comment by Bricksider** [comment]
> Not really an issue with HedgeModManager. GameBanana is currently experiencing an outage.

Thanks for answering.

**Comment by thesupersonic16** [comment]
GameBanana servers are now running. It should no-longer crash when downloading mods.

I may also add a message when a 404 errors occurs incase the servers go down again in the future.

Closing.

Blog: [https://gamebanana.com/blogs/19106](https://gamebanana.com/blogs/19106)
