### ISSUE TITLE
It won't even start up for Sonic Generations, please help

### ISSUE THREAD

**Issue by Giberish4** [thesupersonic16/HedgeModManager#164]
HMM Info:
```
    Version: 7.2-9
    Args: 
    StartDir: C:\Program Files\Genshin Impact\Sonic Generations\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: UnauthorizedAccessException
    Message: Access to the path 'C:\Program Files\Genshin Impact\Sonic Generations\Sonic Generations\cpkredir.ini' is denied.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.CPKREDIRConfig.Save(String path)
       at HedgeModManager.CPKREDIRConfig..ctor(String path)
       at HedgeModManager.HedgeApp.FindAndSetLocalGame()
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by Sajidur78** [comment]
Does running HMM as admin help? looks like HMM is not privileged to write the config file.

**Comment by thesupersonic16** [comment]
As a note to this issue closure, we do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam.
