### ISSUE TITLE
[Sonic Forces] HedgeModManager runs into an error the moment it boots up

### ISSUE THREAD

**Issue by FastestDan** [thesupersonic16/HedgeModManager#175]
HMM Info:
```
    Version: 7.2-9
    Args: 
    StartDir: E:\ProgrammFiles\Sonic Forces\build\main\projects\exec\
    Process Level: User
    Game: Sonic Forces
    SteamGame: Sonic Forces
```

Exception:
```
    Type: TypeLoadException
    Message: Не удалось загрузить тип "System.ValueTuple`2" из сборки "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089".
    Source: HedgeModManager
    Function: Void CheckCodeCompatibility()
    StackTrace: 
       at HedgeModManager.MainWindow.CheckCodeCompatibility()
       at HedgeModManager.MainWindow.RefreshMods()
       at HedgeModManager.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
       at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
       at MS.Internal.LoadedOrUnloadedOperation.DoWork()
       at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
       at System.Windows.Media.MediaContext.FireInvokeOnRen

**Comment by Sajidur78** [comment]
Sorry for the late response, seems like you have an outdated version of .NET Framework. You need to have at least .NET Framework 4.7.2.

**Comment by FastestDan** [comment]
Thanks!
