### ISSUE TITLE
[Sonic Forces] 

### ISSUE THREAD

**Issue by metalsonicdx** [thesupersonic16/HedgeModManager#182]
HMM Info:
```
    Version: 7.2-9
    Args: 
    StartDir: C:\Program Files (x86)\Sonic Forces\build\main\projects\exec\
    Process Level: User
    Game: Sonic Forces
    SteamGame: Sonic Forces
```

Exception:
```
    Type: UnauthorizedAccessException
    Message: Access to the path 'C:\Program Files (x86)\Sonic Forces\build\main\projects\exec\cpkredir.ini' is denied.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.CPKREDIRConfig.Save(String path)
       at HedgeModManager.CPKREDIRConfig..ctor(String path)
       at HedgeModManager.HedgeApp.FindAndSetLocalGame()
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by thesupersonic16** [comment]
We do not support non-Steam/pirated versions of Sonic Forces. Please install the game normally using Steam. Closing.
