### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by Rian578** [thesupersonic16/HedgeModManager#185]
HMM Info:
```
    Version: 7.2-9
    Args: 
    StartDir: C:\Program Files (x86)\SEGA\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: UnauthorizedAccessException
    Message: Access to the path 'C:\Program Files (x86)\SEGA\Sonic Generations\cpkredir.ini' is denied.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.CPKREDIRConfig.Save(String path)
       at HedgeModManager.CPKREDIRConfig..ctor(String path)
       at HedgeModManager.HedgeApp.FindAndSetLocalGame()
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by Rian578** [comment]
please help I can not enter the mod manager

**Comment by thesupersonic16** [comment]
Does rebooting and updating to 7.2-11 help?

**Comment by Rian578** [comment]
ok

**Comment by Rian578** [comment]
yes?

**Comment by Rian578** [comment]
please download link

**Comment by thesupersonic16** [comment]
[Download HedgeModManager 7.3-0](https://github.com/thesupersonic16/HedgeModManager/releases/download/7.3-0/HedgeModManager.exe)

Does this issue always happen?

**Comment by thesupersonic16** [comment]
We do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam. Closing.
