### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by SonicTheHedgehog12121** [thesupersonic16/HedgeModManager#195]
HMM Info:
```
    Version: 7.3-0
    Args: 
    StartDir: C:\Program Files (x86)\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: UnauthorizedAccessException
    Message: Access to the path 'C:\Program Files (x86)\Sonic Generations\cpkredir.ini' is denied.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.CPKREDIRConfig.Save(String path)
       at HedgeModManager.MainWindow.<SaveModsDB>d__14.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<>c__DisplayClass30_0.<<UI_SaveAndPlay_Click>b__0>d.MoveNext()
    InnerException: 
```

Explain : Hello I downloaded a mod for Sonic Generations, And press Save and Play but it gives me this error, My saves didn't really gone but it gets me this.

**Comment by thesupersonic16** [comment]
We do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam. Closing.

**Comment by SonicTheHedgehog12121** [comment]
Hello , Thanks for the Tip but i find a way to fix it anyways Starting
HedgeMod as Administor makes it work.

SuperSonic16 ***@***.***>, 29 Mar 2021 Pzt, 18:42 tarihinde
şunu yazdı:
