### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by X6765** [thesupersonic16/HedgeModManager#217]
HMM Info:
```
    Version: 7.3-4
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: ArgumentNullException
    Message: Value cannot be null.
Parameter name: path2
    Source: mscorlib
    Function: System.String Combine(System.String, System.String)
    StackTrace: 
       at System.IO.Path.Combine(String path1, String path2)
       at HedgeModManager.HedgeApp.FindAndSetLocalGame()
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by X6765** [comment]
So in hedge Mod Manager I just tried to switch from Sonic forces to Sonic Generations but it did not work do someone know why?
Thanks for the help

**Comment by thesupersonic16** [comment]
Can you please send the snapshot file that was generated when you posted this issue? It should be in `C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations` and should start with `HMM_Snapshot_`. Please send the newest one.
