### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by Unwilled** [thesupersonic16/HedgeModManager#237]
[HMM_Snapshot_00052021182056.txt](https://github.com/thesupersonic16/HedgeModManager/files/6565535/HMM_Snapshot_00052021182056.txt)
HMM Info:
```
    Version: 7.4-1
    Args: 
    StartDir: D:\Steam games\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: IOException
    Message: The process cannot access the file 'D:\Steam games\steamapps\common\Sonic Generations\cpkredir.ini' because it is being used by another process.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.CPKREDIRConfig.Save(String path)
       at HedgeModManager.MainWindow.<SaveModsDB>d__22.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<<ComboBox_ModProfile_SelectionChanged>b__66_0>d.MoveNext()
    InnerException: 
```

**Comment by thesupersonic16** [comment]
We currently cannot reproduce this issue for us to fix this issue. Please provide any information if you can on what you were doing and if you can still reproduce this issue or not. 
Some useful information can be like, do you have currently or had ran the game before recently and what you were doing that caused this issue.
