### ISSUE TITLE
Reverted my save file to how it was before I installed HedgeModManager.

### ISSUE THREAD

**Issue by Arcaden06** [thesupersonic16/HedgeModManager#25]
The majority of my progress and avatars are now gone. I started HedgeModManager and it gave me an error message. I pressed Save and Play and booted up the game to find that my avatars were gone. I then realized that all progress made since installing the mod manager was gone. I checked the log and it gave me this: 
`[2018/02/23 17:29:17]: Starting Hedge Mod Manager (v6.1-019)...
[2018/02/23 17:29:17]: Running Hedge Mod Manager in C:\Program Files (x86)\Steam\steamapps\common\SonicForces\build\main\projects\exec
[2018/02/23 17:29:17]: Found Sonic Forces.
[2018/02/23 17:29:17]: Found ModsDB, loading mods...
[2018/02/23 17:29:17]:     11 / 22 mods are active.
[2018/02/23 17:29:17]: Loaded total 22 mods from "C:\Program Files (x86)\Steam\steamapps\common\SonicForces\build\main\projects\exec\mods".
[2018/02/23 17:29:17]: Succesfully updated list view!
[2018/02/23 17:29:17]: Checking for Updates...
[2018/02/23 17:29:18]: Exception thrown while checking for HedgeModManager updates.
[2018/02/23 17:29:18]:     Exception: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at HedgeModManager.MainForm.CheckForModLoaderUpdates()
[2018/02/23 17:29:18]:     Extra Data: 
[2018/02/23 17:29:47]: Found ModsDB, loading mods...
[2018/02/23 17:29:47]:     10 / 22 mods are active.
[2018/02/23 17:29:47]: Loaded total 22 mods from "C:\Program Files (x86)\Steam\steamapps\common\SonicForces\build\main\projects\exec\mods".
[2018/02/23 17:29:47]: Succesfully updated list view!
[2018/02/23 17:29:47]: ModsDB Saved
[2018/02/23 17:29:47]: Starting Sonic Forces...`
I'm very upset about this. I haven't played Forces since 3 days ago and everything was fine then. I (admittedly without really thinking about it) pressed "restore from backup" after all of this and still no luck. I think I messed it up more by doing that, but this still shouldn't have happened in the first place. 
EDIT: and I tried uninstalling the mods using the Settings tab of HMM, but still no luck. Welp, that's 35 hours of unlocks and achievements I'm never getting back.
EDIT 2: Great. I pressed Install again to use the mods with the ruined save file and now Sonic Forces will only launch if mods are uninstalled. I backed up my mods and uninstalled and reinstalled the game. **If you're reading this, don't be like me. Back up your save file OFTEN!**

**Comment by thesupersonic16** [comment]
Please backup every action you do to your save file, Do you still have your savefile.xml(in the savedata folder)?
If you do then you can atleast revert to back before Forces had a save file fix.

**Comment by thesupersonic16** [comment]
Also the error that showed up is not related to the save file, Its a change on Github.

**Comment by thesupersonic16** [comment]
Closing due to the issue not getting a response and now being irrelevant to the current versions of HMM.
