### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by Tal1538** [thesupersonic16/HedgeModManager#267]
HMM Info:
```
    Version: 7.5-0
    Args: 
    StartDir: C:\Program Files\Tal\Sonic Generations\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: Boolean <RefreshProfiles>b__14_1(HedgeModManager.ModProfile)
    StackTrace: 
       at HedgeModManager.MainWindow.<>c.<RefreshProfiles>b__14_1(ModProfile t) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 87
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
       at HedgeModManager.MainWindow.RefreshProfiles() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 70
    InnerException: 
```

**Comment by Tal1538** [comment]
HedgeModManager

- Sonic Generations

**Comment by Tal1538** [comment]
how i fix that?

**Comment by Tal1538** [comment]
![image](https://user-images.githubusercontent.com/84993688/124387830-b610a680-dce8-11eb-89a1-53275a598ff6.png)

**Comment by Tal1538** [comment]
![image](https://user-images.githubusercontent.com/84993688/124387842-c032a500-dce8-11eb-908b-50ad12d2a16e.png)

**Comment by thesupersonic16** [comment]
We do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam. Closing.
