### ISSUE TITLE
[Sonic Generations] [HedgeModManager] Type: TypeInitializationException Error

### ISSUE THREAD

**Issue by Jmcsbsp** [thesupersonic16/HedgeModManager#268]
HMM Info:
```
    Version: 7.5-0
    Args: 
    StartDir: D:\Steam\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: TypeInitializationException
    Message: The type initializer for 'HedgeModManager.CodeProvider' threw an exception.
    Source: HedgeModManager
    Function: System.Threading.Tasks.Task CompileCodes(System.Collections.Generic.IEnumerable`1[HedgeModManager.Code], System.String, System.String[])
    StackTrace: 
       at HedgeModManager.CodeProvider.CompileCodes(IEnumerable`1 sources, String assemblyPath, String[] loadsPaths) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\CodeProvider.cs:line 80
       at HedgeModManager.ModsDB.<SaveDB>d__27.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__22.MoveNext() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 411
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__32.MoveNext() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 714
    InnerException: System.IO.InvalidDataException: Found invalid data while decoding.
   at HedgeModManager.CodeProvider..cctor()
```

**Comment by Sajidur78** [comment]
Hi, what version of Windows are you using?

**Comment by Jmcsbsp** [comment]
Thanks for responding, I’m using Windows 10.

**Comment by thesupersonic16** [comment]
Does updating your .NET Framework help with your issue?

[.NET Framework 4.8](https://go.microsoft.com/fwlink/?linkid=2088631)

**Comment by Jmcsbsp** [comment]
I already have the latest version of that as well.

**Comment by thesupersonic16** [comment]
We might need a snapshot of your config files, might be possible they are corrupted. To do this while HedgeModManager is running and in focus, hold Shift and press F1 then release the Shift key. A popup and explorer window will show up. Send that txt file here.

**Comment by Jmcsbsp** [comment]
[HMM_Snapshot_00072021025226.txt](https://github.com/thesupersonic16/HedgeModManager/files/6775004/HMM_Snapshot_00072021025226.txt)

**Comment by Jmcsbsp** [comment]
Turns out that it works after all. Despite the error still popping up, everything works as it should except for the codes. (Note: I have to press the individual save and play buttons instead of the actual save & play button for this to work. Thanks for helping me out!)
