### ISSUE TITLE
Help :(

### ISSUE THREAD

**Issue by Dart0412** [thesupersonic16/HedgeModManager#275]
HMM Info:
```
    Version: 7.1-4
    Args: 
    StartDir: C:\Users\pc\Documents\Juegos\SONIC GENERATIONS\
    Process Level: Administrator
    Game: Unnamed Game
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.Combine(String path1, String path2)
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.App.Main(String[] args)
    InnerException: 
```

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam. Closing.
