### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by GustavinhoXbox** [thesupersonic16/HedgeModManager#284]
[HMM_Snapshot_00072021221608.txt](https://github.com/thesupersonic16/HedgeModManager/files/6871722/HMM_Snapshot_00072021221608.txt)
HMM Info:
```
    Version: 7.5-0
    Args: 
    StartDir: C:\Program Files (x86)\SEGA\Sonic Generations\
    Process Level: Administrator
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: IOException
    Message: The process cannot access the file 'C:\Program Files (x86)\SEGA\Sonic Generations\mods\Codes.dll' because it is being used by another process.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.CodeProvider.CompileCodes(IEnumerable`1 sources, String assemblyPath, String[] loadsPaths) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\CodeProvider.cs:line 82
       at HedgeModManager.ModsDB.<SaveDB>d__27.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Syste

**Comment by ActualMandM** [comment]
Did you install this via the disc version of the game? If so, can you try reinstalling it via Steam?

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam. Closing.
