### ISSUE TITLE
[Sonic Forces] 

### ISSUE THREAD

**Issue by Gustavoelpro** [thesupersonic16/HedgeModManager#285]
HMM Info:
```
    Version: 7.3-4
    Args: 
    StartDir: C:\Program Files (x86)\Sonic Forces\build\main\projects\exec
    Process Level: User
    Game: Sonic Forces
    SteamGame: Sonic Forces
```

Exception:
```
    Type: UnauthorizedAccessException
    Message: Access to the path 'C:\Program Files (x86)\Sonic Forces\build\main\projects\exec\cpkredir.ini' is denied.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.CPKREDIRConfig.Save(String path)
       at HedgeModManager.MainWindow.<SaveModsDB>d__14.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<<UI_Save_Click>b__29_0>d.MoveNext()
    InnerException: 
```

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Forces. Please install the game normally using Steam. Closing.

**Comment by Sajidur78** [comment]
Tip: try running HMM as admin or reinstall your game to another location outside of Program Files
