### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by Pablovania** [thesupersonic16/HedgeModManager#298]
HMM Info:
```
    Version: 7.4-1
    Args: -gb hedgemmgens:https://gamebanana.com/mmdl/639629,Mod,314919
    StartDir: D:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.String Build(GameBananaAPI.GBAPIItemData)
    StackTrace: 
       at GameBananaAPI.GBAPI.GBAPIRequestHandler.Build(GBAPIItemData item)
       at GameBananaAPI.GBAPI.RequestItemData(GBAPIItemDataBasic& item)
       at GameBananaAPI.GBAPI.ParseCommandLine(String line)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by Knuxfan24** [comment]
GameBanana seems to be having some technical problems that is breaking the One-Click Install function on various Mod Managers, just download the mod manually for now.

**Comment by thesupersonic16** [comment]
The issue on the server seems to have been resolved. At-least on my end it is. Reopen the issue if the issue still persists.
