### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by ojhern24** [thesupersonic16/HedgeModManager#312]
HMM Info:
```
    Version: 7.3-0
    Args: 
    StartDir: D:\Programs\PC\Modding\Sonic Generations\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by RagdollClash** [comment]
Update HedgeModManager to the [latest](https://github.com/thesupersonic16/HedgeModManager/releases/latest) version, as Steam updated their library format some time ago.
