### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by MaroWeeb** [thesupersonic16/HedgeModManager#315]
[HMM_Snapshot_00092021160627.txt](https://github.com/thesupersonic16/HedgeModManager/files/7162582/HMM_Snapshot_00092021160627.txt)
HMM Info:
```
    Version: 7.4-2
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by RagdollClash** [comment]
Update HedgeModManager to the [latest](https://github.com/thesupersonic16/HedgeModManager/releases/latest) version, as Steam updated their library format some time ago.
