### ISSUE TITLE
sonic generations hedgehog manager

### ISSUE THREAD

**Issue by KingVegito** [thesupersonic16/HedgeModManager#318]
HMM Info:
```
    Version: 7.2-5
    Args: 
    StartDir: D:\steam games\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Please update to the [latest](https://github.com/thesupersonic16/HedgeModManager/releases/latest) version of HedgeModManager first.

**Comment by RagdollClash** [comment]
Like what @thesupersonic16 said, update HedgeModManager to the [latest](https://github.com/thesupersonic16/HedgeModManager/releases/latest) version. Steam updated their library format some time ago.
