### ISSUE TITLE
fatal opening error (nvr md needed update)

### ISSUE THREAD

**Issue by Eclipse2025** [thesupersonic16/HedgeModManager#319]
HMM Info:
```
    Version: 7.2-7
    Args: 
    StartDir: D:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```
[HMM_Snapshot_00092021064553.txt](https://github.com/thesupersonic16/HedgeModManager/files/7217300/HMM_Snapshot_00092021064553.txt)

**Comment by Eclipse2025** [comment]
just needed update, nvrmd

**Comment by thesupersonic16** [comment]
Mind letting me know where you got that version? Seems there are a lot of people not updating.
