### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by shyboss2001** [thesupersonic16/HedgeModManager#324]
HMM Info:
```
    Version: 7.4-1
    Args: 
    StartDir: C:\Users\Z-Files\Desktop\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```
[HMM_Snapshot_00092021223335.txt](https://github.com/thesupersonic16/HedgeModManager/files/7240557/HMM_Snapshot_00092021223335.txt)

**Comment by RagdollClash** [comment]
Update HedgeModManager to the [latest](https://github.com/thesupersonic16/HedgeModManager/releases/latest) version, as Steam updated their library format some time ago.

**Comment by shyboss2001** [comment]
Ok
