### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by DanSoll** [thesupersonic16/HedgeModManager#325]
HMM Info:
```
    Version: 7.3-2
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```
[HMM_Snapshot_00092021005053.txt](https://github.com/thesupersonic16/HedgeModManager/files/7249159/HMM_Snapshot_00092021005053.txt)

**Comment by thesupersonic16** [comment]
This crash was already fixed and released in 7.4-3. Please update to the [newest version](https://github.com/thesupersonic16/HedgeModManager/releases/latest) of HedgeModManager.
