### ISSUE TITLE
[SonicGenerations] HELP! IT WON'T STOP THROWING THIS ERROR 

### ISSUE THREAD

**Issue by ivonnesaysmiau** [thesupersonic16/HedgeModManager#327]
HMM Info:
```
    Version: 7.6-0
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: TypeInitializationException
    Message: The type initializer for 'HedgeModManager.CodeProvider' threw an exception.
    Source: HedgeModManager
    Function: System.Threading.Tasks.Task CompileCodes(System.Collections.Generic.IEnumerable`1[HedgeModManager.Code], System.String, System.String[])
    StackTrace: 
       at HedgeModManager.CodeProvider.CompileCodes(IEnumerable`1 sources, String assemblyPath, String[] loadsPaths) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\CodeProvider.cs:line 68
       at HedgeModManager.ModsDB.<SaveDB>d__27.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__36.MoveNext() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 429
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__46.MoveNext() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 736
    InnerException: System.TypeLoadException: Could not load type 'System.Object' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' because the parent does not exist.
   at HedgeModManager.CodeProvider..cctor()
```

**Comment by ivonnesaysmiau** [comment]
I remember that i once activated the All walls being wall jumpable cheat, and after i turned it off this error started popping up, and even though the cheat is deactivated it somehow is still on!

**Comment by thesupersonic16** [comment]
I don't think this is a configuration issue, but just in case, can you send the snapshot file? It should be located in the Sonic Generations folder starting in HMM_Snapshot_

**Comment by ivonnesaysmiau** [comment]
Can't seem to find it in the folder.

**Comment by thesupersonic16** [comment]
Weird, should be in there. You can still generate a new one by pressing Shift + F1 while the HMM window is in focus.

**Comment by ivonnesaysmiau** [comment]
Which HMM window?

**Comment by thesupersonic16** [comment]
The main one which shows all the mods.
