### ISSUE TITLE
[SonicGenerations]  HELP, everytime i try to run sonic generations with the mod manager this happens

### ISSUE THREAD

**Issue by TheREALRawBerry** [thesupersonic16/HedgeModManager#335]
HMM Info:
```
    Version: 7.6-0
    Args: 
    StartDir: C:\Users\Admin\OneDrive\Escritorio\Bruh\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: Win32Exception
    Message: El usuario ha cancelado la operación
    Source: System
    Function: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
    StackTrace: 
       at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 439
       at HedgeModManager.MainWindow.<SaveConfig>d__46.MoveNext() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 739
    InnerException: 
```

**Comment by TheREALRawBerry** [comment]
I'm trying to play STH2006 mod but everytime i try to run the game with it, it crashes
