### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by Bomb234** [thesupersonic16/HedgeModManager#336]
HMM Info:
```
    Version: 7.6-0-4d81400
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.InternalGetDirectoryName(String path)
       at HedgeModManager.HedgeApp.FindAndSetLocalGame() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 397
       at HedgeModManager.HedgeApp.Main(String[] args) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 200
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Was a snapshot file generated when you submitted this report? If so can you send it here?
