### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by TheBlueEM2** [thesupersonic16/HedgeModManager#344]
[HMM_Snapshot_00112021172347.txt](https://github.com/thesupersonic16/HedgeModManager/files/7597670/HMM_Snapshot_00112021172347.txt)
HMM Info:
```
    Version: 7.6-0
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: UnauthorizedAccessException
    Message: Access to the path 'C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\mods\Codes.dll' is denied.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.CodeProvider.CompileCodes(IEnumerable`1 sources, String assemblyPath, String[] loadsPaths) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\CodeProvider.cs:line 70
       at HedgeModManager.ModsDB.<SaveDB>d__27.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__36.MoveNext() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 429
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__46.MoveNext() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 736
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Are you able to consistently reproduce this issue?

**Comment by TheBlueEM2** [comment]
Yes. This happens every time I hit save when trying to load mods.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by thesupersonic16** [comment]
Can you send the snapshot file that should have been generated when the issue occurred? A popup should show up when you clicked the report button, if not let me know anyways.

**Comment by TheBlueEM2** [comment]
I'll send it tomorrow morning.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
