### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by victorman101** [thesupersonic16/HedgeModManager#346]
HMM Info:
```
    Version: 7.4-1
    Args: 
    StartDir: C:\Users\victo\OneDrive\Desktop\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Please update to [7.6-1](https://github.com/thesupersonic16/HedgeModManager/releases/download/7.6-1/HedgeModManager.exe) and let me know if this solves your issue or not.
