### ISSUE TITLE
Sonic Generation Mod Manager

### ISSUE THREAD

**Issue by SpoodySTK** [thesupersonic16/HedgeModManager#353]
HMM Info:
```
    Version: 7.6-1
    Args: 
    StartDir: D:\SteamLibrary\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Unnamed Game
    Update Status: Up To Date
```

Exception:
```
    Type: XamlParseException
    Message: 'Cannot create unknown type '{clr-namespace:HedgeModManager.Languages}LanguageList'.' Line number '6' and line position '6'.
    Source: PresentationFramework
    Function: Void RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
    StackTrace: 
       at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
       at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
       at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
       at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
       at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode, Boolean useRestrictiveXamlReader, List`1 safeTypes)
       at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext, Boolean useRestrictiveXamlReader)
       at HedgeModManager.HedgeApp.GetLanguageResource(String culture) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 415
       at HedgeModManager.HedgeApp.CountLanguages() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 426
       at HedgeModManager.HedgeApp.Main(String[] args) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 171
    InnerException: System.Xaml.XamlObjectWriterException: 'Cannot create unknown type '{clr-namespace:HedgeModManager.Languages}LanguageList'.' Line number '6' and line position '6'.
   at System.Xaml.XamlObjectWriter.WriteStartObject(XamlType xamlType)
   at System.Windows.Markup.WpfXamlLoader.WriteStartObject(XamlReader xamlReader, XamlObjectWriter xamlWriter, XamlContextStack`1 stack)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
```

**Comment by thesupersonic16** [comment]
Make sure the Languages folder only contains language file(s) and not the file containing the list of languages (Languages.xaml)

Let me know if this solves the issue or not.

**Comment by SpoodySTK** [comment]
> Make sure the Languages folder only contains language file(s) and not the file containing the list of languages (Languages.xaml)
> 
> Let me know if this solves the issue or not.

Nope. I moved the Language.Xaml to the root. Should I delete it?
