### ISSUE TITLE
HedgeModManager

### ISSUE THREAD

**Issue by samzilla42** [thesupersonic16/HedgeModManager#356]
HMM Info:
```
    Version: 7.2-6
    Args: 
    StartDir: E:\Games\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```
[HMM_Snapshot_00122021180000.txt](https://github.com/thesupersonic16/HedgeModManager/files/7731547/HMM_Snapshot_00122021180000.txt)

**Comment by Sajidur78** [comment]
Update HMM to latest
