### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by chuater** [thesupersonic16/HedgeModManager#366]
HMM Info:
```
    Version: 7.2-6
    Args: 
    StartDir: E:\Downloads\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Please update HedgeModManager to the [latest](https://github.com/thesupersonic16/HedgeModManager/releases/latest) version.
