### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by reneamora467** [thesupersonic16/HedgeModManager#368]
HMM Info:
```
    Version: 7.6-2
    Args: 
    StartDir: C:\Users\Amora\Documents\HedgeModManager\
    Process Level: User
    Game: Unnamed Game
    Update Status: Up To Date
```

Exception:
```
    Type: XamlParseException
    Message: 'Cannot create unknown type '{clr-namespace:HedgeModManager.Languages}LanguageList'.' Line number '6' and line position '6'.
[HMM_Snapshot_00012022195650.txt](https://github.com/thesupersonic16/HedgeModManager/files/7850776/HMM_Snapshot_00012022195650.txt)

    Source: PresentationFramework
    Function: Void RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
    StackTrace: 
       at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
       at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
       at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
       at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
       at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode, Boolean useRestrictiveXamlReader, List`1 safeTypes)
       at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext, Boolean useRestrictiveXamlReader)
       at HedgeModManager.HedgeApp.GetLanguageResource(String culture) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 415
       at HedgeModManager.HedgeApp.CountLanguages() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 426
       at HedgeModManager.HedgeApp.Main(String[] args) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 171
    InnerException: System.Xaml.XamlObjectWriterException: 'Cannot create unknown type '{clr-namespace:HedgeModManager.Languages}LanguageList'.' Line number '6' and line position '6'.
   at System.Xaml.XamlObjectWriter.WriteStartObject(XamlType xamlType)
   at System.Windows.Markup.WpfXamlLoader.WriteStartObject(XamlReader xamlReader, XamlObjectWriter xamlWriter, XamlContextStack`1 stack)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
```

**Comment by thesupersonic16** [comment]
Were you working on a translation?

**Comment by reneamora467** [comment]
I wasn't. I actually haven't started up the program in a while and I wanted to play. Then I got hit with this

**Comment by thesupersonic16** [comment]
Do you have a Languages folder next to the exe file?

**Comment by reneamora467** [comment]
I do see a languages folder in the directory

**Comment by thesupersonic16** [comment]
Did you create the folder? If not, either move the exe somewhere else, delete the folder or rename the folder to something else. The folder should only exist next to the exe if you are working on a translation.

**Comment by reneamora467** [comment]
That worked, thanks!

**Comment by thesupersonic16** [comment]
Not sure why you had the folder to begin with. But good to hear it is working for you. I will be closing this issue, reply if the same/relevant issue occurs.
