### ISSUE TITLE
i cant open the modmanager

### ISSUE THREAD

**Issue by sountail** [thesupersonic16/HedgeModManager#369]
I downloaded sonic generations and i want to play some unleashed mods so i installed hedgemodmanager but when i open it this happens and i think my computer deletes the app instantly any way i can solve this? plz

HMM Info:
```
    Version: 7.6-2
[HMM_Snapshot_00012022232736.txt](https://github.com/thesupersonic16/HedgeModManager/files/7859931/HMM_Snapshot_00012022232736.txt)

    Args: 
    StartDir: C:\Windows\SM\steamapps\common\Sonic Generations\mods\HedgeModManager-7.6-2\HedgeModManager-7.6-2\HedgeModManager\
    Process Level: User
    Game: Unnamed Game
    Update Status: Up To Date
```

Exception:
```
    Type: XamlParseException
    Message: 'Cannot create unknown type '{clr-namespace:HedgeModManager.Languages}LanguageList'.' Line number '6' and line position '6'.
    Source: PresentationFramework
    Function: Void RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
    StackTrace: 
       at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
       at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
       at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri)
       at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext)
       at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext, XamlParseMode parseMode, Boolean useRestrictiveXamlReader, List`1 safeTypes)
       at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext, Boolean useRestrictiveXamlReader)
       at HedgeModManager.HedgeApp.GetLanguageResource(String culture) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 415
       at HedgeModManager.HedgeApp.CountLanguages() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 426
       at HedgeModManager.HedgeApp.Main(String[] args) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 171
    InnerException: System.Xaml.XamlObjectWriterException: 'Cannot create unknown type '{clr-namespace:HedgeModManager.Languages}LanguageList'.' Line number '6' and line position '6'.
   at System.Xaml.XamlObjectWriter.WriteStartObject(XamlType xamlType)
   at System.Windows.Markup.WpfXamlLoader.WriteStartObject(XamlReader xamlReader, XamlObjectWriter xamlWriter, XamlContextStack`1 stack)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
```

**Comment by thesupersonic16** [comment]
This is the third time someone has reported this exact same crash. Where did you download this from?

Also I recommend moving HMM elsewhere like your desktop, and make sure HMM is an exception on your anti-virus as it commonly gets false positives.

**Comment by sountail** [comment]
im going to do that and i downloaded it from gamebanana and after that i came here to github

**Comment by sountail** [comment]
@thesupersonic16 thank you i touched some things in my computer and it worked, and sorry if i bothered you i know i am not the first  and the last one coming here with problems so thank you
<3

**Comment by thesupersonic16** [comment]
Can you please tell me where on GameBanana you downloaded HedgeModManager? What you have told me does not match up with what I have uploaded on GameBanana at all.
