### ISSUE TITLE
Crash when adding a new code and saving 

### ISSUE THREAD

**Issue by ghost** [thesupersonic16/HedgeModManager#377]
I added a code and then HMM crashed

HMM Info:
```
    Version: 7.6-2
    Args: 
    StartDir: C:\Users\md1ha\Downloads\Sonic Generations\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Error compiling codes
(3,6): error CS0103: The name 'initialized' does not exist in the current context
(13,23): error CS0103: The name '_0' does not exist in the current context
(14,27): error CS0103: The name '_50_60' does not exist in the current context
(23,2): error CS0103: The name 'initialized' does not exist in the current context

    Source: HedgeModManager
    Function: System.Threading.Tasks.Task CompileCodes(System.Collections.Generic.IEnumerable`1[HedgeModManager.Code], System.IO.Stream, System.String[])
    StackTrace: 
       at HedgeModManager.CodeProvider.CompileCodes(IEnumerable`1 sources, Stream resultStream, String[] loadPaths) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\CodeProvider.cs:line 79
       at HedgeModManager.CodeProvider.CompileCodes(IEnumerable`1 sources, String assemblyPath, String[] loadsPaths) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\CodeProvider.cs:line 72
       at HedgeModManager.ModsDB.<SaveDB>d__27.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__38.MoveNext() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 477
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__50.MoveNext() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 801
    InnerException: 
```

**Comment by Sajidur78** [comment]
Could you send the code you added? Seems like there might be some syntax errors in there.

**Comment by ghost** [comment]
EDIT:it works now after i enable and disable them multiple times

i added 2 codes first:Patch "Unleashed Voice Swap" by "brianuuu"
WriteProtected<byte>(0x123196F, 0x14);
WriteProtected<uint>(0x1231971, 0x2DCE9D); /*Lightdash*/
WriteProtected<uint>(0xE4B684, 0xFFFFFF); /*Tricks (disable)*/
WriteProtected<byte>(0xE4B8DE, 0x14);
WriteProtected<uint>(0xE4B8E0, 0x2DCE9D); /*Trick finish*/
WriteProtected<uint>(0xDF3710, 0x2DCEA3); /*Drift*/
WriteProtected<byte>(0xDF0C06, 0x14);
WriteProtected<uint>(0xDF0C08, 0x2DCE9D); /*4-way cannon (false direction on Unleashed jump selector)*/
WriteProtected<byte>(0xDF0B94, 0x14);
WriteProtected<uint>(0xDF0B96, 0x2DCE9D); /*true direction on Unleashed jump selector (Unused in Generations)*/


The 2nd code is:Patch "Collect 10-Ring Instantly" by "brianuuu"
WriteNop(0xE4155E, 2);
WriteNop(0xE415C8, 2);
WriteProtected<int>(0xE4157A, -1);
Code "Infinite Rings" by "SuperSonic16"
Write<uint>(GetPointer(0x1E5E2F0, 0x5B8), 0x3E7)

**Comment by thesupersonic16** [comment]
Is the issue fully solved? if so please close the issue.
