### ISSUE TITLE
Issue installing sm64 generations

### ISSUE THREAD

**Issue by Student3589015** [thesupersonic16/HedgeModManager#387]
HMM Info:
```
    Version: 7.2-5
    Args: -gb hedgemmgens:https://gamebanana.com/mmdl/775415,Mod,368411
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by Sajidur78** [comment]
Your HMM version is incredibly outdated, get the current version from releases.
