### ISSUE TITLE
Sonic Generations Mod Manager Crash on start

### ISSUE THREAD

**Issue by 01-BlackHawk-11** [thesupersonic16/HedgeModManager#390]
HMM Info:
```
    Version: 7.4-2
    Args: 
    StartDir: F:\Games\Sonic Generations\
    Process Level: Administrator
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
[HMM_Snapshot_00042022213114.txt](https://github.com/thesupersonic16/HedgeModManager/files/8446636/HMM_Snapshot_00042022213114.txt)

```

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam. Closing.
