### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by Yeetus6921** [thesupersonic16/HedgeModManager#397]
When I try to start the game pressing "Save and Play" the message appears. Mods with codes also don't work but I'm not sure if that is related.

[HMM_Snapshot_00042022185233.txt](https://github.com/thesupersonic16/HedgeModManager/files/8567381/HMM_Snapshot_00042022185233.txt)

HMM Info:
```
    Version: 7.7-0-e3e2f80
    Args: 
    StartDir: C:\Program Files (x86)\R.G. Catalyst\Sonic Generations\
    Process Level: Administrator
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: ArgumentNullException
    Message: Value cannot be null.
Parameter name: path1
    Source: mscorlib
    Function: System.String Combine(System.String, System.String)
    StackTrace: 
       at System.IO.Path.Combine(String path1, String path2)
       at HedgeModManager.GameInstall.StartGame(Boolean useLauncher, String startDirectory) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\Game.cs:line 201
       at HedgeModManager.MainWindow.StartGame() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 495
       at HedgeModManager.MainWindow.<SaveConfig>d__50.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 811
    InnerException: 
```

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam.

Closing.
