### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by MetalBoyJony** [thesupersonic16/HedgeModManager#407]
HMM Info:
```
    Version: 7.2-11
    Args: -gb hedgemmforces:https://gamebanana.com/mmdl/371116,Mod,250519
    StartDir: C:\Users\sjoni\AppData\Local\Temp\Temp1_sonichedemodnmanager7211 (1).zip\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Please update HedgeModManager to the [latest](https://github.com/thesupersonic16/HedgeModManager/releases/latest) version.
