### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by Sonicboom93** [thesupersonic16/HedgeModManager#415]
HMM Info:
```
    Version: 7.2-6
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Lost World\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by RagdollClash** [comment]
Try updating HedgeModManager to [7.7](https://github.com/thesupersonic16/HedgeModManager/releases/tag/7.7).
