### ISSUE TITLE
[SonicForces] 

### ISSUE THREAD

**Issue by Dogu373** [thesupersonic16/HedgeModManager#431]
HMM Info:
```
    Version: 7.7-0
    Args: 
    StartDir: C:\Users\QUADRO\Downloads\Sonic.Forces.Incl.All.DLC's\Sonic Forces\build\main\projects\exec\
    Process Level: Administrator
    Game: Sonic Forces
    GameInstall: Sonic Forces
    Update Status: Up To Date
```

Exception:
```
    Type: ArgumentNullException
    Message: Value cannot be null.
Parameter name: path1
    Source: mscorlib
    Function: System.String Combine(System.String, System.String)
    StackTrace: 
       at System.IO.Path.Combine(String path1, String path2)
       at HedgeModManager.GameInstall.StartGame(Boolean useLauncher, String startDirectory) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\Game.cs:line 201
       at HedgeModManager.MainWindow.StartGame() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 495
       at HedgeModManager.MainWindow.<SaveConfig>d__50.MoveNext() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 811
    InnerException: 
```

**Comment by thesupersonic16** [comment]
We do not support non-Steam/pirated versions of Sonic Forces. Please install the game normally using Steam.

Closing.
