### ISSUE TITLE
Sonic generations Hedgehmod Manager

### ISSUE THREAD

**Issue by KazooDillk** [thesupersonic16/HedgeModManager#456]
HMM Info:
```
    Version: 7.2-9
    Args: 
    StartDir: D:\Documents\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by RagdollClash** [comment]
Try using the [latest version](https://github.com/thesupersonic16/HedgeModManager/releases/latest) of HedgeModManager. You are on 7.2-9 while the current version is [7.8-1](https://github.com/thesupersonic16/HedgeModManager/releases/tag/7.8-1).
