### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by Volt790** [thesupersonic16/HedgeModManager#468]
HMM Info:
```
    Version: 7.3-4
    Args: 
    StartDir: C:\Users\Volt790\Documents\Games\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

[HMM_Snapshot_00092022194827.txt](https://github.com/thesupersonic16/HedgeModManager/files/9501549/HMM_Snapshot_00092022194827.txt)

**Comment by thesupersonic16** [comment]
Please update HedgeModManager to the [latest](https://github.com/thesupersonic16/HedgeModManager/releases/latest) version.
