### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by IUNOU123** [thesupersonic16/HedgeModManager#469]
HMM Info:
```
    Version: 7.8-0
    Args: 
    StartDir: D:\SteamLibrary\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Update Ignored
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.InternalGetDirectoryName(String path)
       at HedgeModManager.HedgeApp.FindAndSetLocalGame() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 445
       at HedgeModManager.HedgeApp.Main(String[] args) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 213
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Can you please upload the snapshot txt file and tell me If you have Steam and/or Epic Games Launcher installed?
