### ISSUE TITLE
Force refuses to start after HMM loaded

### ISSUE THREAD

**Issue by RiPerils** [thesupersonic16/HedgeModManager#48]
Following on from https://github.com/thesupersonic16/HedgeModManager/issues/38 

The game runs the title cards and then crashes before the main title screen can load.
I have run the recommended .bat files to remove HMM, re-installed HMM and no change.

No mods have yet been put into the folder, the game is refusing to load with or without mods in place.

**Comment by Sajidur78** [comment]
Could you try using the rewrite version and see if the issue persists? https://ci.appveyor.com/project/thesupersonic16/slw-mod-loader/build/job/lgret747fnnc9oq8/artifacts

**Comment by RiPerils** [comment]
Thats loaded with no mods first go.

Then i put some mods put some mods in and got the following error.
I removed and reloaded the HMM provided, put mods back in and still stopped. 

HMM Info:
    Version: 7.0-dev
    Args: 
    StartDir: E:\Steam\steamapps\common\SonicForces\build\main\projects\exec\
    Process Level: User
    Game: Sonic Forces
    SteamGame: SteamGame {SteamID: 637100, GameName: Sonic Forces, EXE: E:\Steam\steamapps\common\SonicForces\build\main\projects\exec\Sonic Forces.exe}

Exception:
    Type: FormatException
    Message: Input string was not in a correct format.
    Source: mscorlib
    Function: Void StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
    StackTrace: 
       at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
       at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
       at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
       at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
       at HedgeModManager.Serialization.IniSerializer.<Deserialize>g__ReadField|2_0(String group, String name, Type valueType, <>c__DisplayClass2_0& ) in C:\projects\slw-mod-loader\HedgeModManager\Serialization\IniSerializer.cs:line 152
       at HedgeModManager.Serialization.IniSerializer.Deserialize(Object obj, Stream stream) in C:\projects\slw-mod-loader\HedgeModManager\Serialization\IniSerializer.cs:line 115
       at HedgeModManager.CPKREDIRConfig..ctor(String path) in C:\projects\slw-mod-loader\HedgeModManager\Config\CPKREDIRConfig.cs:line 64
       at HedgeModManager.App.Main(String[] args) in C:\projects\slw-mod-loader\HedgeModManager\App.xaml.cs:line 138
    InnerException:

**Comment by Sajidur78** [comment]
could you upload your cpkredir.ini?

**Comment by RiPerils** [comment]
The file is completes blank, it has no data in it and 0kb filesize
[cpkredir.zip](https://github.com/thesupersonic16/HedgeModManager/files/4003627/cpkredir.zip)

**Comment by thesupersonic16** [comment]
Yeah that ini is corrupted. Can you try deleting that file and reopening HMM?

**Comment by RiPerils** [comment]
That fixes the HMM crashing on running HMM and the game can be played with out mods.
Trying to load a mod re-created the .ini and results in a crash on game start up. it also crashed on ticking a mod on the list  and clicking save. 

HMM Info:
```
    Version: 7.0-dev
    Args: 
    StartDir: E:\Steam\steamapps\common\SonicForces\build\main\projects\exec
    Process Level: User
    Game: Sonic Forces
    SteamGame: SteamGame {SteamID: 637100, GameName: Sonic Forces, EXE: E:\Steam\steamapps\common\SonicForces\build\main\projects\exec\Sonic Forces.exe}
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: mscorlib
    Function: System.Type GetType()
    StackTrace: 
       at System.Object.GetType()
       at HedgeModManager.Serialization.IniSerializer.<Serialize>g__WriteValue|0_0(String name, String group, Object value, <>c__DisplayClass0_0& ) in C:\projects\slw-mod-loader\HedgeModManager\Serialization\IniSerializer.cs:line 47
       at HedgeModManager.Serialization.IniSerializer.Serialize(Object obj, Stream stream) in C:\projects\slw-mod-loader\HedgeModManager\Serialization\IniSerializer.cs:line 28
       at HedgeModManager.CPKREDIRConfig.Save(String path) in C:\projects\slw-mod-loader\HedgeModManager\Config\CPKREDIRConfig.cs:line 90
       at HedgeModManager.MainWindow.SaveModsDB() in C:\projects\slw-mod-loader\HedgeModManager\UI\MainWindow.xaml.cs:line 149
       at HedgeModManager.MainWindow.UI_SaveAndPlay_Click(Object sender, RoutedEventArgs e) in C:\projects\slw-mod-loader\HedgeModManager\UI\MainWindow.xaml.cs:line 273
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.Controls.Primitives.ButtonBase.OnClick()
       at System.Windows.Controls.Button.OnClick()
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at HedgeModManager.App.Main(String[] args) in C:\projects\slw-mod-loader\HedgeModManager\App.xaml.cs:line 142
    InnerException: 
```

**Comment by Sajidur78** [comment]
Try using this version it had some serialization fixes. https://ci.appveyor.com/project/thesupersonic16/slw-mod-loader/branch/rewrite/job/2h95dga7r27375f4/artifacts

**Comment by RiPerils** [comment]
I was ill for the last week and lost track of all this, only just now getting back to things.

**Comment by RagdollClash** [comment]
Any update on this issue?

**Comment by thesupersonic16** [comment]
We were not given information about how the new built went.

**Comment by RiPerils** [comment]
https://ci.appveyor.com/project/thesupersonic16/slw-mod-loader/branch/rewrite/job/2h95dga7r27375f4/artifacts
I cant see the file on that link to grab and try the mod manger again with a fresh install
I cleared my files of a while back and don't have a copy any more.

**Comment by thesupersonic16** [comment]
Use this [link](https://ci.appveyor.com/project/thesupersonic16/slw-mod-loader/build/job/2yhwxpm84p4a6o7f/artifacts) instead.

**Comment by RiPerils** [comment]
Right, that's worked okay.
The game has loaded several times without mods, so I've put some mods in and its loaded okay, trying a few more in.
