### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by Athon5787** [thesupersonic16/HedgeModManager#54]
HMM Info:
    Version: 7.0-0
    Args: 
    StartDir: C:\Users\ferha\Desktop\
    Process Level: Administrator
    Game: Unnamed Game
    SteamGame: 

Exception:
    Type: InvalidOperationException
    Message: Sequence contains no elements
    Source: System.Core
    Function: TSource First[TSource](System.Collections.Generic.IEnumerable`1[TSource])
    StackTrace: 
       at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
       at HedgeModManager.App.Main(String[] args)
    InnerException:

**Comment by thesupersonic16** [comment]
Do you have any of the three supported games installed on Steam?

The information given is a bit lacking, but from what I can get from that is it couldn't find your game. If its not installed in a registered Steam library you will have to copy the exe into your game's directory.

Edit: Fixed 1ce1e18c65387c6fcaba6716f5933b35dc344f61, Let me know if what I wrote helped or not.

**Comment by thesupersonic16** [comment]
Closing due to inactivity with a fix. If this fix does not resolve your issue, then please reopen this issue.
