### ISSUE TITLE
Crash on SCU Steam

### ISSUE THREAD

**Issue by Twanvanb1** [thesupersonic16/HedgeModManager#583]
HMM Info:
    Version: 7.9-0-cb4490a
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicColorsUltimate\exec
    Process Level: User
    Game: Sonic Colors: Ultimate
    GameInstall: Sonic Colors: Ultimate

Exception:
    Type: MissingMethodException
    Message: Method not found: 'System.ReadOnlySpan`1<!0> System.Collections.Immutable.ImmutableArray`1.AsSpan()'.
    Source: Microsoft.CodeAnalysis
    Function: Boolean IsValidPublicKey(System.Collections.Immutable.ImmutableArray`1[System.Byte])
    StackTrace: 
       at Microsoft.CodeAnalysis.CryptoBlobParser.IsValidPublicKey(ImmutableArray`1 blob)
       at Microsoft.CodeAnalysis.MetadataReaderExtensions.CreateAssemblyIdentityOrThrow(MetadataReader reader, Version version, AssemblyFlags flags, BlobHandle publicKey, StringHandle name, StringHandle culture, Boolean isReference) in /_/src/Compilers/Core/Portable/MetadataReader/MetadataReaderExtensions.cs:line 144
       at Microsoft.CodeAnalysis.MetadataReaderExtensions.ReadAssemblyIdentityOrThrow(MetadataReader reader) in /_/src/Compilers/Core/Portable/MetadataReader/MetadataReaderExtensions.cs:line 47
       at Microsoft.CodeAnalysis.PEAssembly..ctor(AssemblyMetadata owner, ImmutableArray`1 modules) in /_/src/Compilers/Core/Portable/MetadataReader/PEAssembly.cs:line 59
       at Microsoft.CodeAnalysis.AssemblyMetadata.GetOrCreateData() in /_/src/Compilers/Core/Portable/MetadataReference/AssemblyMetadata.cs:line 343
       at Microsoft.CodeAnalysis.AssemblyMetadata.GetModules() in /_/src/Compilers/Core/Portable/MetadataReference/AssemblyMetadata.cs:line 283
       at Microsoft.CodeAnalysis.AssemblyMetadata.IsValidAssembly() in /_/src/Compilers/Core/Portable/MetadataReference/AssemblyMetadata.cs:line 410
       at Microsoft.CodeAnalysis.CommonReferenceManager`2.GetMetadata(PortableExecutableReference peReference, CommonMessageProvider messageProvider, Location location, DiagnosticBag diagnostics) in /_/src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Resolution.cs:line 494
       at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveMetadataReferences(TCompilation compilation, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectiveMap, ImmutableArray`1& boundReferenceDirectives, ImmutableArray`1& assemblies, ImmutableArray`1& modules, DiagnosticBag diagnostics) in /_/src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Resolution.cs:line 324
       at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(CSharpCompilation compilation) in /_/src/Compilers/CSharp/Portable/Symbols/ReferenceManager.cs:line 357
       at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(CSharpCompilation compilation) in /_/src/Compilers/CSharp/Portable/Symbols/ReferenceManager.cs:line 184
       at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetRuntimeMetadataVersion(EmitOptions emitOptions) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 3476
       at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetRuntimeMetadataVersion(EmitOptions emitOptions, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 3459
       at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CreateModuleBuilder(EmitOptions emitOptions, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, IEnumerable`1 manifestResources, CompilationTestData testData, DiagnosticBag diagnostics, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 3130
       at Microsoft.CodeAnalysis.Compilation.CheckOptionsAndCreateModuleBuilder(DiagnosticBag diagnostics, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 3115
       at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream metadataPEStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, RebuildData rebuildData, CompilationTestData testData, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 2874
       at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, RebuildData rebuildData, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 2831
       at HedgeModManager.CodeProvider.CompileCodes(IEnumerable`1 sources, Stream resultStream, String[] loadPaths) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\CodeProvider.cs:line 101
       at HedgeModManager.CodeProvider.CompileCodes(IEnumerable`1 sources, String assemblyPath, String[] loadsPaths) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\CodeProvider.cs:line 80
       at HedgeModManager.ModsDB.<SaveDB>d__27.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 645
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 976
    InnerException: 

[HMM_Snapshot_00022023112137.txt](https://github.com/thesupersonic16/HedgeModManager/files/10684350/HMM_Snapshot_00022023112137.txt)

**Comment by Twanvanb1** [comment]
I got this when pressing save
