### ISSUE TITLE
Launches the Epic version of SCU after launching the Steam Version and doesn't work after uninstalling the Epic Version. The game directory and mod directory are both from Steam

### ISSUE THREAD

**Issue by All-StarsPixel** [thesupersonic16/HedgeModManager#584]
HMM Info:
```
    Version: 7.9-0-cb4490a
    Args: 
    StartDir: E:\SteamLibrary\steamapps\common\SonicColorsUltimate\exec
    Process Level: User
    Game: Sonic Colours: Ultimate
    GameInstall: Sonic Colours: Ultimate
    Update Status: Up To Date
```

Exception:
```
    Type: Win32Exception
    Message: The system cannot find the file specified
    Source: System
    Function: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
    StackTrace: 
       at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 660
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 978
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Thanks for letting us know of this issue, do you have Use Game Launcher enabled in the settings?

**Comment by All-StarsPixel** [comment]
> Thanks for letting us know of this issue, do you have Use Game Launcher enabled in the settings?

I'm pretty sure. I'll check later

**Comment by All-StarsPixel** [comment]
> > Thanks for letting us know of this issue, do you have Use Game Launcher enabled in the settings?
> 
> I'm pretty sure. I'll check later

i think i broke my game when editing appdata. not even steam works when launching it
