### ISSUE TITLE
[SonicForces] 

### ISSUE THREAD

**Issue by William201119** [thesupersonic16/HedgeModManager#585]
It won't update other components than the Hedgemodmanager itself (except for the mods though). No matter what I do it always gives me this warning:

"WARNING
The installed codes are incompatible with the code loader. Please update the codes and the code loader.
WARNING: This will erase any custom codes."

Pressing UPDATE just gaves identical errors, so I have no clue how to fix this. An update or any help would be greatly appreciated!
Feel free to send me an e-mail if you have any helpful suggestions: william201119@gmail.com

(ALSO, it has worked previously with a former version, and I have the .exe inside every supported Sonic game folder. I have also tried the developer-version, but that made no difference...)

![Skjermbilde (627)](https://user-images.githubusercontent.com/124940152/217960382-be63b3ec-bcbf-4233-ba81-ded319df8427.png)

HMM Info:
```
    Version: 7.9-0-cb4490a
    Args: 
    StartDir: D:\SteamLibrary\steamapps\common\SonicForces\build\main\projects\exec
    Process Level: User
    Game: Sonic Forces
    GameInstall: Sonic Forces
    Update Status: Up To Date
```

Exception:
```
    Type: Win32Exception
    Message: Ingen tilgang
    Source: System
    Function: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
    StackTrace: 
       at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 660
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 978
    InnerException: 
```

**Comment by William201119** [comment]
I am also completely unable to install the modloader to use the mods in any of the apps... And the warning goes away when all the codes are deleted, but... they are only the downloaded community codes. :/ Very wierd... :(

Here is another error, if it helps...

HMM Info:
```
    Version: 7.9-0
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: Win32Exception
    Message: Ingen tilgang
    Source: System
    Function: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
    StackTrace: 
       at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in E:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 660
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in E:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 978
    InnerException: 
```

**Comment by William201119** [comment]
Somehow works now, I think...
Weird...
