### ISSUE TITLE
[Bug] Unable to download mods error: illegal characters in path

### ISSUE THREAD

**Issue by Aaquin** [thesupersonic16/HedgeModManager#609]
I keep getting the error: illegal characters in path, as an error when downloading mods from GameBanana. The games are sonic frontiers and Sonic colors, both are installed with steam on my e drive

**Comment by Aaquin** [comment]
update: it does the same for Sonic generations too it is on the same drive

**Comment by thesupersonic16** [comment]
Not sending the entire crash info does not help. Either send the snapshot (the file generated by pressing the submit button) or the crash info from the crash window.

**Comment by Aaquin** [comment]
An error has occurred during the download. servers might be down or overloaded. Please try again later.

Details: Illegal characters in path. 

this all that shows when I attempt it retrying it says the same thing and puts a zip of the mod in the folder the mod loader is in. attempting to manually install the mods gives me:

HMM Info:
```
    Version: 7.9-0-1301bd0
    Args: 
    StartDir: E:\SteamLibrary\steamapps\common\SonicColorsUltimate\exec
    Process Level: User
    Game: Sonic Colors: Ultimate
    GameInstall: Sonic Colors: Ultimate
    Update Status: Up To Date
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.Combine(String path1, String path2)
       at HedgeModManager.ModsDB.<>c.<InstallModArchiveUsing7Zip>b__35_0(String s) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\ModsDB.cs:line 318
       at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
       at HedgeModManager.ModsDB.InstallModArchiveUsing7Zip(String path, String root) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\ModsDB.cs:line 317
       at HedgeModManager.ModsDB.InstallModArchive(String path, String root) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\ModsDB.cs:line 276
       at HedgeModManager.MainWindow.UI_Install_Mod(Object sender, RoutedEventArgs e) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1338
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.Controls.Primitives.ButtonBase.OnClick()
       at System.Windows.Controls.Button.OnClick()
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at HedgeModManager.HedgeApp.Main(String[] args) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 276
    InnerException: 
```

**Comment by Aaquin** [comment]
The recent update fixed my issue
