### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by REEFY274** [thesupersonic16/HedgeModManager#613]
HMM Info:
```
    Version: 7.9-0
    Args: 
    StartDir: D:\SteamLibrary\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: IOException
    Message: The media is write protected.

    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
       at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
       at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in E:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 973
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Can you confirm if you are still having the issue?
