### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by stephen-netu** [thesupersonic16/HedgeModManager#619]
HMM Info:
```
    Version: 7.9-0
    Args: 
    StartDir: D:\Games\Steam\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.Combine(String path1, String path2)
       at HedgeModManager.ModsDB.<>c.<InstallModArchiveUsing7Zip>b__35_0(String s) in E:\GitHub\HedgeModManager\HedgeModManager\ModsDB.cs:line 312
       at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
       at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
       at HedgeModManager.ModsDB.InstallModArchiveUsing7Zip(String path, String root) in E:\GitHub\HedgeModManager\HedgeModManager\ModsDB.cs:line 311
       at HedgeModManager.ModsDB.InstallModArchive(String path, String root) in E:\GitHub\HedgeModManager\HedgeModManager\ModsDB.cs:line 270
       at HedgeModManager.MainWindow.UI_Install_Mod(Object sender, RoutedEventArgs e) in E:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1338
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.Controls.Primitives.ButtonBase.OnClick()
       at System.Windows.Controls.Button.OnClick()
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at HedgeModManager.HedgeApp.Main(String[] args) in E:\GitHub\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 272
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Can you please tell me what mod you are installing?

**Comment by stephen-netu** [comment]
https://gamebanana.com/mods/420414 - The Combat DX one from here.

**Comment by Vo-one** [comment]
> This information indicates that an "ArgumentException" type exception was thrown in the program while executing a method that tries to concatenate two path strings into one.

Specifically, the exception was thrown from the "CheckInvalidPathChars" method of the "System.IO.Path" class, which checks for invalid characters in a file system path.
The call stack (StackTrace) indicates that the exception was thrown from the "InstallModArchiveUsing7Zip" method in the "HedgeModManager.ModsDB" class, which tries to install a modification for the game from the archive using the 7-Zip utility, using the path to the root directory of the game.

InnerException is not specified,
but it usually contains more information about the exception.

In general, this may be because the file path contains invalid characters such as special characters, spaces, or invalid encoding characters. The solution to the problem may be to change the file path or remove invalid characters from the path. If possible,
try changing the path to the root directory of the game so that it does not contain invalid characters. If this does not help, then the problem may be with the 7-Zip program, which may not be able to handle certain types of files or file paths. In this case,
you can try changing the mod installer or install the mod manually without using the 7-Zip utility. It is also worth making sure that you have the latest version of the program installed and that you are using the correct version for your operating system.
