### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by LilactheFox** [thesupersonic16/HedgeModManager#644]
[HMM_Snapshot_00062023155244.txt](https://github.com/thesupersonic16/HedgeModManager/files/11779875/HMM_Snapshot_00062023155244.txt)

HMM Info:
```
    Version: 7.10-0
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.InternalGetDirectoryName(String path)
       at HedgeModManager.HedgeApp.FindAndSetLocalGame() in E:\Git\hedgemodmanager\HedgeModManager\HedgeApp.xaml.cs:line 343
       at HedgeModManager.HedgeApp.Main(String[] args) in E:\Git\hedgemodmanager\HedgeModManager\HedgeApp.xaml.cs:line 228
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Your CPKREDIR config is corrupted, you will either need to fix it or just reset it by deleting the `cpkredir.ini`. Also do not use SonicGMI after you install HMM.
