### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by pedro1847** [thesupersonic16/HedgeModManager#658]
direct3d9 ex mod caused this crash

[HMM_Snapshot_00072023142252.txt](https://github.com/thesupersonic16/HedgeModManager/files/11939763/HMM_Snapshot_00072023142252.txt)

HMM Info:
```
    Version: 7.10-0
    Args: 
    StartDir: C:\Program Files (x86)\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: UnauthorizedAccessException
    Message: Access to the path 'C:\Program Files (x86)\Sonic Generations\Mods\GenerationsD3D9Ex\GenerationsD3D9Ex.ini' is denied.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.UI.FormSchema.SaveIni(String path) in E:\Git\hedgemodmanager\He

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam.

Closing.
