### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by ajas264** [thesupersonic16/HedgeModManager#663]
HMM Info:
```
    Version: 7.10-0
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.InternalGetDirectoryName(String path)
       at HedgeModManager.HedgeApp.FindAndSetLocalGame() in E:\Git\hedgemodmanager\HedgeModManager\HedgeApp.xaml.cs:line 343
       at HedgeModManager.HedgeApp.Main(String[] args) in E:\Git\hedgemodmanager\HedgeModManager\HedgeApp.xaml.cs:line 228
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Can you please upload the snapshot .txt file that was generated when you clicked on the report button?
