### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by SonicFan345** [thesupersonic16/HedgeModManager#67]
HMM Info:
    Version: 7.0-4
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations

Exception:
    Type: IOException
    Message: The process cannot access the file 'C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\SonicGenerations.exe' because it is being used by another process.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
       at HedgeModManager.App.InstallCPKREDIR(String executablePath, Nullable`1 install)
       at HedgeModManager.App.Main(String[] args)
    InnerException:

**Comment by thesupersonic16** [comment]
@Sajidur78 didn't we remove this feature?
Also for the original poster, can you try closing Generations before opening HMM?

**Comment by thesupersonic16** [comment]
Sorry for the long delay. It seems it crashed when it tried to make sure CPKREDIR is not patched. Mind checking if HMM still crashes when you launch HMM?

**Comment by thesupersonic16** [comment]
This Issue has already been fixed in 43f2941f1438bdd72c4ad2df64e19cd450e78db9

**Comment by SonicFan345** [comment]
Ok I’m gonna check tmm

**Comment by thesupersonic16** [comment]
Use [HedgeModManager.zip](https://github.com/thesupersonic16/HedgeModManager/files/4966553/HedgeModManager.zip) Its built to that commit.

**Comment by thesupersonic16** [comment]
Sorry, messed up the link. [HedgeModManager.zip](https://github.com/thesupersonic16/HedgeModManager/files/4966553/HedgeModManager.zip)
