### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by Yawhnn** [thesupersonic16/HedgeModManager#670]
anytime i try to load the game through hmm with mods i get an error. how to fix?

[HMM_Snapshot_00072023173203.txt](https://github.com/thesupersonic16/HedgeModManager/files/12198626/HMM_Snapshot_00072023173203.txt)

HMM Info:
```
    Version: 7.10-0
    Args: 
    StartDir: D:\steam\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Error compiling codes
(14,46): error CS1003: Syntax error, ',' expected

    Source: HedgeModManager
    Function: System.Threading.Tasks.Task CompileCodes[TCollection](TCollection, System.IO.Stream, System.String[])
    StackTrace: 
       at HedgeModManager.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, String[] loadPaths) in E:\Git\hedgemodmanager\HedgeModManager\CodeProvider.cs:line 113
       at HedgeModManager.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, String[] loadsPaths) in E:\Git\hedgemodmanager\HedgeModManager\CodeProvider.cs:line 71
       at HedgeModManager.ModsDB.<SaveDB>d__27.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in E:\Git\hedgemodmanager\HedgeModManager\UI\MainWindow.xaml.cs:line 650
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in E:\Git\hedgemodmanager\HedgeModManager\UI\MainWindow.xaml.cs:line 981
    InnerException: 
```

**Comment by Goji54** [comment]
I also had this problem

**Comment by Sajidur78** [comment]
The issue is unrelated to HMM and more than likely just a bad Codes.hmm or a bad code file in one of the mods.

Try disabling `Enhanced Juke Box + Fixes` and updating/redownloading community codes.
