### ISSUE TITLE
[SonicFrontiers] Hedge Mod Manager has thrown an exception Report

### ISSUE THREAD

**Issue by HighHaddock** [thesupersonic16/HedgeModManager#678]
HMM Info:
```
    Version: 7.10-1-1959ff2
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.String Resolve(System.String)
    StackTrace: 
       at HedgeModManager.ModsDB.Resolve(String name) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\ModsDB.cs:line 541
       at HedgeModManager.CodeCompiler.PreProcessor.TextProcessor.Process(String text)
       at HedgeModManager.CodeCompiler.SyntaxTreeEx.ProcessText(String text, TextProcessor& preprocessor, IIncludeResolver includeResolver)
       at HedgeModManager.CodeCompiler.SyntaxTreeEx.Parse(String text, IIncludeResolver includeResolver)
       at HedgeModManager.CodeCompiler.CodeProvider.GetLoadAssemblies[TCollection](TCollection sources, IIncludeResolver includeResolver, String[] lookupPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, IIncludeResolver includeResolver, String[] loadPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 655
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 986
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Sorry for the delay, can you provide the snapshot .txt file that was generated when you created the issue and if this issue stills occurs.

**Comment by Ebicmodder** [comment]
i have the same error so can i give my snapshot.txt?

**Comment by thesupersonic16** [comment]
You can send your snapshot file.

**Comment by Ebicmodder** [comment]
[HMM_Snapshot_00082023092310.txt](https://github.com/thesupersonic16/HedgeModManager/files/12333496/HMM_Snapshot_00082023092310.txt)

**Comment by Ebicmodder** [comment]
i found what may be causing the problem and it might be a mod called "open zone drift" because once I turned that off the error wouldn't appear

**Comment by thesupersonic16** [comment]
Which version of the mod do you have exactly?

**Comment by thesupersonic16** [comment]
Also if you can, try updating your community codes.

**Comment by Sajidur78** [comment]
@HighHaddock Make sure your community codes are updated
