### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by blartiocrump** [thesupersonic16/HedgeModManager#680]
I haven't booted up the game in maybe a month now and now the game doesn't open at all. HMM gives this error and i've tried to boot the game with the mod loader off and still nothing. 

[HMM_Snapshot_00082023092420.txt](https://github.com/thesupersonic16/HedgeModManager/files/12327433/HMM_Snapshot_00082023092420.txt)

HMM Info:
```
    Version: 7.10-1-1959ff2
    Args: 
    StartDir: F:\SteamLibrary\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Unable to find dependency library Time
    Source: HedgeModManager.CodeCompiler
    Function: System.Threading.Tasks.Task CompileCodes[TCollection](TCollection, System.IO.Stream, HedgeModManager.CodeCompiler.PreProcessor.IIncludeResolver, System.String[])
    StackTrace: 
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, IIncludeResolver includeResolver, String[] loadPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 655
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 986
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Have you tried updating the community codes list before saving?

**Comment by blartiocrump** [comment]
no, im dumb asf THANK YOUUUUU it fixed <3

**Comment by thesupersonic16** [comment]
Good to hear you solved your issue. Closing.
