### ISSUE TITLE
[SonicFrontiers] Hedge Mod Manager won't work 

### ISSUE THREAD

**Issue by Wahlver** [thesupersonic16/HedgeModManager#681]
<
[HMM_Snapshot_00082023004511.txt](https://github.com/thesupersonic16/HedgeModManager/files/12341553/HMM_Snapshot_00082023004511.txt)
!-- Please explain below any relevant information which may have caused this crash like steps to reproduce the issue -->

HMM Info:
```
    Version: 7.10-2
    Args: 
    StartDir: D:\SteamLibrary\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Unable to find dependency library Sonic
    Source: HedgeModManager.CodeCompiler
    Function: System.Threading.Tasks.Task CompileCodes[TCollection](TCollection, System.IO.Stream, HedgeModManager.CodeCompiler.PreProcessor.IIncludeResolver, System.String[])
    StackTrace: 
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, IIncludeResolver includeResolver, String[] loadPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 655
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 991
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Did you make sure to update the community codes?

**Comment by Wahlver** [comment]
I'm not sure what that is, I'm new to this. How do I update the community codes?

**Comment by thesupersonic16** [comment]
Click this button.
![image](https://github.com/thesupersonic16/HedgeModManager/assets/25761885/b1ede710-de2c-41de-9f24-28dc696838ec)

**Comment by Wahlver** [comment]
Ah, I think that did the trick! The game actually loaded
