### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by BirdQuest** [thesupersonic16/HedgeModManager#687]
[HMM_Snapshot_00082023125732.txt](https://github.com/thesupersonic16/HedgeModManager/files/12371856/HMM_Snapshot_00082023125732.txt)
## Describe the issue/bug

I clicked save and the mod manager crashed
HMM Info:
```
    Version: 7.10-2-2506984
    Args: 
    StartDir: E:\SteamLibrary\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Error compiling codes
(11,62): error CS0103: The name 'GetAssetName' does not exist in the current context

    Source: HedgeModManager.CodeCompiler
    Function: System.Threading.Tasks.Task CompileCodes[TCollection](TCollection, System.IO.Stream, HedgeModManager.CodeCompiler.PreProcessor.IIncludeResolver, System.String[])
    StackTrace: 
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, IIncludeResolver includeResolver, String[] loadPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 655
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 986
    InnerException: 
```

## Expected Behaviour

I was expecting the mod manager to save my mod list when I clicked save on Sonic Frontiers, but it crashed instead.
## Additional Context

Sonic Generations has a similar issue where I sometimes can't drag and reorder my mods and results in a crash as soon as I hold the left click.

**Comment by BirdQuest** [comment]
I think I already fixed the problem
