### ISSUE TITLE
[Unnamed Game] 

### ISSUE THREAD

**Issue by Infinite0000** [thesupersonic16/HedgeModManager#688]
HMM Info:
```
    Version: 7.2-7
    Args: -gb hedgemmgens:https://gamebanana.com/mmdl/931861,Mod,426185
    StartDir: C:\Users\aidia\Downloads\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by RagdollClash** [comment]
Please update HedgeModManager to the latest version. Closing.
