### ISSUE TITLE
[SonicOrigins] 

### ISSUE THREAD

**Issue by Ebridger26** [thesupersonic16/HedgeModManager#689]
I really don't know what happened to cause it, but here are my mods listed:

![Screenshot 2023-08-19 215927](https://github.com/thesupersonic16/HedgeModManager/assets/125831518/4cda2181-b97c-47c4-9e58-62e6729bc17a)

[HMM_Snapshot_00082023215331.txt](https://github.com/thesupersonic16/HedgeModManager/files/12387135/HMM_Snapshot_00082023215331.txt)

HMM Info:
```
    Version: 7.10-2-2506984
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicOrigins\build\main\projects\exec
    Process Level: User
    Game: Sonic Origins
    GameInstall: Sonic Origins
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Error compiling codes
(2,34): error CS0103: The name 'Reflection' does not exist in the current context
(8,2): error CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
(8,43): error CS0103: The name 'stringData' does not exist in the current context
(2,26): error CS0103: The name 'Reflection' does not exist in the current context
(6,2): error CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
(6,35): error CS0103: The name 'm_RetroSfxSonic2' does not exist in the current context
(7,2): error CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
(7,35): error CS0103: The name 'm_RetroSfxSonicCD' does not exist in the current context

    Source: HedgeModManager.CodeCompiler
    Function: System.Threading.Tasks.Task CompileCodes[TCollection](TCollection, System.IO.Stream, HedgeModManager.CodeCompiler.PreProcessor.IIncludeResolver, System.String[])
    StackTrace: 
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, IIncludeResolver includeResolver, String[] loadPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 655
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 986
    InnerException: 
```

**Comment by hyperbx** [comment]
Update your community codes via the Codes tab.
