### ISSUE TITLE
[SonicOrigins] 

### ISSUE THREAD

**Issue by BTTFdude** [thesupersonic16/HedgeModManager#693]
[HMM_Snapshot_00082023120239.txt](https://github.com/thesupersonic16/HedgeModManager/files/12410558/HMM_Snapshot_00082023120239.txt)

HMM Info:
```
    Version: 7.10-2
    Args: 
    StartDir: E:\SteamLibrary\steamapps\common\SonicOrigins\build\main\projects\exec
    Process Level: User
    Game: Sonic Origins
    GameInstall: Sonic Origins
    Update Status: Up To Date
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: Void <Serialize>g__WriteValue|3_0(System.String, System.String, System.Object, System.Type, <>c__DisplayClass3_0 ByRef)
    StackTrace: 
       at HedgeModManager.Serialization.IniSerializer.<Serialize>g__WriteValue|3_0(String name, String group, Object value, Type valueType, <>c__DisplayClass3_0& ) in F:\Git\HedgeModManager\HedgeModManager\Serialization\IniSerializer.cs:line 131
       at HedgeModManager.Serialization.IniSerializer.Serialize(Object obj, IniFile file) in F:\Git\HedgeModManager\HedgeModManager\Serialization\IniSerializer.cs:line 76
       at HedgeModManager.Serialization.IniSerializer.Serialize(Object obj, Stream stream) in F:\Git\HedgeModManager\HedgeModManager\Serialization\IniSerializer.cs:line 59
       at HedgeModManager.ModInfo.Save() in F:\Git\HedgeModManager\HedgeModManager\ModInfo.cs:line 210
       at HedgeModManager.MainWindow.UI_Edit_Mod(Object sender, RoutedEventArgs e) in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1306
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at HedgeModManager.HedgeApp.Main(String[] args) in F:\Git\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 279
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Can you explain what mod you were editing that caused this issue?

**Comment by BTTFdude** [comment]
Hi,

I was downloading an update of a mod called "Original Remaster SFX Pack" by
MegAmi, which I got from gamebanana.com (https://gamebanana.com/sounds/61847
).
The instructions said to delete the old version of that mod before
downloading and installing the new version (2.6.1). After doing so and upon
running HedgeModManager with "Original Remaster SFX Pack" enabled, the
program crashes. It does not crash if I uncheck the mod in the main menu. I
also can't seem to download an older version of the mod to verify if those
work.
Please let me know if you need more information.

Thank you,
Chris (BTTFdude)

**Comment by thesupersonic16** [comment]
I am unable to reproduce this crash. You may need to try narrowing down the issue on your end.
