### ISSUE TITLE
[SonicOrigins] 

### ISSUE THREAD

**Issue by BTTFdude** [thesupersonic16/HedgeModManager#694]
[HMM_Snapshot_00082023120427.txt](https://github.com/thesupersonic16/HedgeModManager/files/12410569/HMM_Snapshot_00082023120427.txt)

HMM Info:
```
    Version: 7.10-2
    Args: 
    StartDir: E:\SteamLibrary\steamapps\common\SonicOrigins\build\main\projects\exec
    Process Level: User
    Game: Sonic Origins
    GameInstall: Sonic Origins
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Error compiling codes
(2,26): error CS0103: The name 'Reflection' does not exist in the current context
(6,2): error CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
(6,35): error CS0103: The name 'm_RetroSfxSonic2' does not exist in the current context
(7,2): error CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
(7,35): error CS0103: The name 'm_RetroSfxSonicCD' does not exist in the current context

    Source: HedgeModManager.CodeCompiler
    Function: System.Threading.Tasks.Task CompileCodes[TCollection](TCollection, System.IO.Stream, HedgeModManager.CodeCompiler.PreProcessor.IIncludeResolver, System.String[])
    StackTrace: 
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, IIncludeResolver includeResolver, String[] loadPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 655
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 991
    InnerException: 
```

**Comment by RagdollClash** [comment]
Update your codes.
