### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by RedAngryBird2009** [thesupersonic16/HedgeModManager#696]
HMM Info:
```
    Version: 7.10-2
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Unable to find dependency library Sonic
    Source: HedgeModManager.CodeCompiler
    Function: System.Threading.Tasks.Task CompileCodes[TCollection](TCollection, System.IO.Stream, HedgeModManager.CodeCompiler.PreProcessor.IIncludeResolver, System.String[])
    StackTrace: 
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, IIncludeResolver includeResolver, String[] loadPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 655
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 991
    InnerException: 
```

**Comment by RagdollClash** [comment]
Update your codes.
