### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by inftord** [thesupersonic16/HedgeModManager#70]
HMM Info:
    Version: 7.0-5
    Args: 
    StartDir: C:\Program Files (x86)\R.G. World Games\Sonic Generations
    Process Level: Administrator
    Game: Sonic Generations
    SteamGame: Sonic Generations

Exception:
    Type: IOException
    Message: The process cannot access the file 'C:\Program Files (x86)\R.G. World Games\Sonic Generations\mods\Codes.dat' because it is being used by another process.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.CodeList.WriteDatFile(String path, IList`1 codes, Boolean is64Bit)
       at HedgeModManager.MainWindow.UI_SaveAndPlay_Click(Object sender, RoutedEventArgs e)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

**Comment by thesupersonic16** [comment]
Did you make sure to close Sonic Generations before clicking Save and Play?

**Comment by thesupersonic16** [comment]
It has been confirmed you are using a pirated version of Sonic Generations which we do not provide support for so I will have to close this issue. Feel free to reopen if you encounter the same issue on the legit Steam version.
