### ISSUE TITLE
[SonicFrontiers] Game won't load with Bounce Bracelet & Drift Mods on

### ISSUE THREAD

**Issue by JakeJackJoe** [thesupersonic16/HedgeModManager#700]
Trying to Save or Save & Play while Loco's Reimagined Drift Experience mod and/or Sr101's Bounce Bracelet mod are checked in the mod manager causes it to load up another window that says "Hedge Mod Manager Has Thrown an Exception!" (this happens regardless if I have any other mods turned on or not). I have tried with both the release and development builds, neither of them can get the game started with these mods on. I had a similar issue with Trepe Serafin's Open Zone Drift Mod but that was solved with changing to the release build. Loco's Drift Mod on the other hand, doesn't seem to work on either build.

[HMM_Snapshot_00082023164930.txt](https://github.com/thesupersonic16/HedgeModManager/files/12446699/HMM_Snapshot_00082023164930.txt)

HMM Info:
```
    Version: 7.10-2-1656791
    Args: Game Folder\HedgeModManager\HedgeModManager.exe
    StartDir: E:\SteamLibrary\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Error compiling codes
(39,13): error CS0117: 'Sonic.State' does not contain a definition for 'Discard'
(49,17): error CS0117: 'Sonic.State' does not contain a definition for 'Discard'
(50,17): error CS0117: 'Sonic.State' does not contain a definition for 'Discard'
(51,17): error CS0117: 'Sonic.State' does not contain a definition for 'Discard'
(77,17): error CS0117: 'Sonic.State' does not contain a definition for 'Discard'
(259,21): error CS0117: 'Sonic.State' does not contain a definition for 'Discard'

    Source: HedgeModManager.CodeCompiler
    Function: System.Threading.Tasks.Task CompileCodes[TCollection](TCollection, System.IO.Stream, HedgeModManager.CodeCompiler.PreProcessor.IIncludeResolver, System.String[])
    StackTrace: 
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, IIncludeResolver includeResolver, String[] loadPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 655
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 986
    InnerException: 
```

**Comment by RagdollClash** [comment]
Update your codes.
