### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by Huksprava** [thesupersonic16/HedgeModManager#703]
[HMM_Snapshot_00082023151446.txt](https://github.com/thesupersonic16/HedgeModManager/files/12448589/HMM_Snapshot_00082023151446.txt)

HMM Info:
```
    Version: 7.10-2
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Error compiling codes
(35,28): error CS0117: 'BlackboardStatus' does not contain a definition for 'IsCyberSpace'
(39,13): error CS0117: 'Sonic.State' does not contain a definition for 'Discard'
(39,27): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(41,46): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(44,31): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(49,17): error CS0117: 'Sonic.State' does not contain a definition for 'Discard'
(49,31): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(50,17): error CS0117: 'Sonic.State' does not contain a definition for 'Discard'
(50,31): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(51,17): error CS0117: 'Sonic.State' does not contain a definition for 'Discard'
(51,31): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(61,18): error CS0117: 'Sonic.Effect' does not contain a definition for 'StopEffect'
(64,46): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(71,35): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(72,35): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(76,32): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(77,17): error CS0117: 'Sonic.State' does not contain a definition for 'Discard'
(77,31): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(120,22): error CS0117: 'Sonic.Effect' does not contain a definition for 'PlayEffect'
(138,50): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(138,120): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(138,193): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(139,36): error CS0117: 'Sonic' does not contain a definition for 'StateID'
(149,36): error CS0117: 'Sonic' does not contain a definition for 'StateID'

    Source: HedgeModManager.CodeCompiler
    Function: System.Threading.Tasks.Task CompileCodes[TCollection](TCollection, System.IO.Stream, HedgeModManager.CodeCompiler.PreProcessor.IIncludeResolver, System.String[])
    StackTrace: 
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, IIncludeResolver includeResolver, String[] loadPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 655
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 991
    InnerException: 
```

**Comment by Sajidur78** [comment]
Update your community codes from the codes tab.
