### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by YayaDream** [thesupersonic16/HedgeModManager#705]
HMM Info:
```
    Version: 7.10-2
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicFrontiers\
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Unable to find dependency library SonicParameters
    Source: HedgeModManager.CodeCompiler
    Function: System.Threading.Tasks.Task CompileCodes[TCollection](TCollection, System.IO.Stream, HedgeModManager.CodeCompiler.PreProcessor.IIncludeResolver, System.String[])
    StackTrace: 
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, IIncludeResolver includeResolver, String[] loadPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 655
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 991
    InnerException: 
```

**Comment by YayaDream** [comment]
I Activate Open Zone Drift And The Sonic X Mod And I Have This Error

**Comment by RagdollClash** [comment]
Update your community codes.

**Comment by YayaDream** [comment]
How ? Idk How Do It Sorry

**Comment by YayaDream** [comment]
Plz

**Comment by thesupersonic16** [comment]
Click this.
![image](https://github.com/thesupersonic16/HedgeModManager/assets/25761885/0c2e4f74-e020-4fa9-99cb-1f4da24dd9d5)

Enabling this can help aswell.
![image](https://github.com/thesupersonic16/HedgeModManager/assets/25761885/0a948486-8c43-4ae8-b8d1-565773f17572)

**Comment by YayaDream** [comment]
Thank you

**Comment by YayaDream** [comment]
THE MODS WORK FINE THXXXXXX
