### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by Shredster7** [thesupersonic16/HedgeModManager#731]
Attempting to save and play the game after receiving the codes update pushed on September 16th throws this exception.

HMM Info:
```
    Version: 7.10-3
    Args: 
    StartDir: D:\SteamLibrary\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Error compiling codes
(5,19): error CS1004: Duplicate 'static' modifier
(24,19): error CS1004: Duplicate 'static' modifier

    Source: HedgeModManager.CodeCompiler
    Function: System.Threading.Tasks.Task CompileCodes[TCollection](TCollection, System.IO.Stream, HedgeModManager.CodeCompiler.PreProcessor.IIncludeResolver, System.String[])
    StackTrace: 
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, IIncludeResolver includeResolver, String[] loadPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 664
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 995
    InnerException: 
```

[HMM_Snapshot_00092023171754.txt](https://github.com/thesupersonic16/HedgeModManager/files/12641589/HMM_Snapshot_00092023171754.txt)

**Comment by hyperbx** [comment]
Should be fixed in commit https://github.com/hedge-dev/HMMCodes/commit/08fdc486c39c1be48542202e26e362e1e85b6dd8, update your community codes.
