### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by Squrtyy** [thesupersonic16/HedgeModManager#734]
Even with no mods enabled I still get this exception.

[HMM_Snapshot_00092023155635.txt](https://github.com/thesupersonic16/HedgeModManager/files/12666026/HMM_Snapshot_00092023155635.txt)

HMM Info:
```
    Version: 7.10-3
    Args: 
    StartDir: D:\SteamLibrary\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: TypeInitializationException
    Message: The type initializer for 'HedgeModManager.CodeCompiler.CodeProvider' threw an exception.
    Source: HedgeModManager.CodeCompiler
    Function: System.Threading.Tasks.Task CompileCodes[TCollection](TCollection, System.String, HedgeModManager.CodeCompiler.PreProcessor.IIncludeResolver, System.String[])
    StackTrace: 
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 664
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 995
    InnerException: System.TypeInitializationException: The type initializer for 'Microsoft.CodeAnalysis.CSharp.SyntaxFactory' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxFactory' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at System.Collections.Immutable.ImmutableArray`1.Builder.IndexOf(T item)
   at Microsoft.CodeAnalysis.GreenNodeExtensions.WithAnnotationsGreen[TNode](TNode node, IEnumerable`1 annotations) in /_/src/Compilers/Core/Portable/Syntax/GreenNodeExtensions.cs:line 19
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxFactory..cctor() in /_/src/Compilers/CSharp/Portable/Syntax/InternalSyntax/SyntaxFactory.cs:line 24
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory..cctor() in /_/src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs:line 30
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.get_ElasticMarker() in /_/src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs:line 90
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.Token(SyntaxKind kind) in /_/src/Compilers/CSharp/Portable/Syntax/SyntaxFactory.cs:line 219
   at HedgeModManager.CodeCompiler.CodeProvider..cctor()
```

**Comment by thesupersonic16** [comment]
Are you still getting the issue?
