### ISSUE TITLE
[SonicColorsUltimate] 

### ISSUE THREAD

**Issue by HighHaddock** [thesupersonic16/HedgeModManager#741]
HMM Info:
```
    Version: 7.10-3
    Args: 
    StartDir: B:\SteamLibrary\steamapps\common\SonicColorsUltimate\exec
    Process Level: User
    Game: Sonic Colors: Ultimate
    GameInstall: Sonic Colors: Ultimate
    Update Status: Up To Date
```

Exception:
```
    Type: Win32Exception
    Message: The system cannot find the file specified
    Source: System
    Function: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
    StackTrace: 
       at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 677
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1002
    InnerException: 
```

**Comment by thesupersonic16** [comment]
Do you have SCU installed in `B:\SteamLibrary\steamapps\common\SonicColorsUltimate`?

**Comment by HighHaddock** [comment]
Yes

**Comment by thesupersonic16** [comment]
Is the game exe in the `B:\SteamLibrary\steamapps\common\SonicColorsUltimate\exec` folder?

**Comment by HighHaddock** [comment]
yes

**Comment by thesupersonic16** [comment]
can you send the snapshot txt file that got generated when you made this issue?

**Comment by HighHaddock** [comment]
i already uninstalled the game and started reinstalling it in my main c drive. I though the issue was that it was in my b drive.

**Comment by HighHaddock** [comment]
I reinstalled it on b drive. What did you want me to do again?

**Comment by HighHaddock** [comment]
![Screenshot 2023-09-21 191541](https://github.com/thesupersonic16/HedgeModManager/assets/97855122/6f5e5f30-d4aa-42c0-9968-c2eecfd17c01)

Here's the snapshot you wanted

**Comment by HighHaddock** [comment]
You still there?

**Comment by thesupersonic16** [comment]
I meant the txt file that should be located next to the HMM exe.

**Comment by HighHaddock** [comment]
There isn't a txt file next to the HMM exe. When I got HedgeModManager, it only came with the exe and didn't use anything else.

**Comment by thesupersonic16** [comment]
Then hold Shift and press F2 and it will generate one.

**Comment by thesupersonic16** [comment]
I mean F1 lol

**Comment by HighHaddock** [comment]
I still don't see it. Where is HedgeModManager usually installed?

**Comment by thesupersonic16** [comment]
HMM is a portable app, it will be wherever you placed it.

**Comment by HighHaddock** [comment]
[HMM_Snapshot_00092023200220.txt](https://github.com/thesupersonic16/HedgeModManager/files/12694300/HMM_Snapshot_00092023200220.txt)
Here you go

**Comment by HighHaddock** [comment]
heres the txt file you wanted

**Comment by HighHaddock** [comment]
you still there?

**Comment by DeaTh-G** [comment]
@thesupersonic16

**Comment by thesupersonic16** [comment]
It appears this may be a bug with how Steam games are launched when the `Use game launcher` option is disabled. To confirm this observation, can you enable the option and see if the game boots up fine from HMM?
