### ISSUE TITLE
[SonicOrigins] 

### ISSUE THREAD

**Issue by dawnofviolence** [thesupersonic16/HedgeModManager#742]
HMM Info:
```
    Version: 7.10-3
    Args: 
    StartDir: S:\games\Steam\steamapps\common\SonicOrigins\build\main\projects\exec
    Process Level: User
    Game: Sonic Origins
    GameInstall: Sonic Origins
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Error compiling codes
(2,26): error CS0103: The name 'Reflection' does not exist in the current context
(6,2): error CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
(6,35): error CS0103: The name 'm_RetroSfxSonic2' does not exist in the current context
(7,2): error CS0103: The name 'RFL_SET_PARAM' does not exist in the current context
(7,35): error CS0103: The name 'm_RetroSfxSonicCD' does not exist in the current context

    Source: HedgeModManager.CodeCompiler
    Function: System.Threading.Tasks.Task CompileCodes[TCollection](TCollection, System.IO.Stream, HedgeModManager.CodeCompiler.PreProcessor.IIncludeResolver, System.String[])
    StackTrace: 
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, IIncludeResolver includeResolver, String[] loadPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 664
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 995
    InnerException: 
```

[HMM_Snapshot_00092023092123.txt](https://github.com/thesupersonic16/HedgeModManager/files/12706868/HMM_Snapshot_00092023092123.txt)

**Comment by dawnofviolence** [comment]
I've just realized this is an issue with the Original Remaster SFX Pack mod, probably doesn't support latest Origins Plus patch

**Comment by Sajidur78** [comment]
@dawnofviolence Try updating community codes, see if that helps. If it doesn't then the mod author has to update it.

**Comment by dawnofviolence** [comment]
That ended up working. Thanks
