### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by DarkYTX** [thesupersonic16/HedgeModManager#748]
Tried Downloading a Mod for Sonic Frontiers via 1 Click Install and for some unknown reason the Modloader crashed,
I made sure my Modloader was on Developer Mod for Frontiers and everytime I try opening the Modloader, I just get the Crashing Massage, is there a way to fix this I tried redownloading HMM and that also didn't solve the Issue

[HMM_Snapshot_00102023190511.txt](https://github.com/thesupersonic16/HedgeModManager/files/12777726/HMM_Snapshot_00102023190511.txt)

HMM Info:
```
    Version: 7.11-1-a8e2a7d
    Args: 
    StartDir: I:\SteamLibrary\steamapps\common\SonicFrontiers\
    Process Level: Administrator
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: JsonReaderException
    Message: Unexpected character encountered while parsing value: �. Path '', line 0, position 0.
    Source: Newtonsoft.Json
    Function: Boolean ParseValue()
    StackTrace: 
       at Newtonsoft.Json.JsonTextReader.ParseValue()
       at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
       at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
       at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
       at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
       at HedgeModManager.MainWindow.RefreshProfiles() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 133
```

[

**Comment by thesupersonic16** [comment]
Your `profiles.json` file is corrupted, can you please delete this file and see if the issue comes back? If it does please let me know of as much details as you can.
