### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by Zelop11** [thesupersonic16/HedgeModManager#77]
HMM Info:
```
    Version: 7.0-7
    Args: 
    StartDir: D:\SteamLibrary\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: IOException
    Message: The process cannot access the file 'D:\SteamLibrary\steamapps\common\Sonic Generations\cpkredir.ini' because it is being used by another process.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.CPKREDIRConfig.Save(String path)
       at HedgeModManager.MainWindow.SaveModsDB()
       at HedgeModManager.MainWindow.UI_SaveAndPlay_Click(Object sender, RoutedEventArgs e)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.Controls.Primitives.ButtonBase.OnClick()
       at System.Windows.Controls.Button.OnClick()
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at HedgeModManager.App.Main(String[] args)
    InnerException: 
```

**Comment by Zelop11** [comment]
I can't launch the game with the mod loader and neither the game from the steam platform. Can you help me?

**Comment by thesupersonic16** [comment]
Does rebooting your PC fix the issue?

**Comment by Zelop11** [comment]
No, the problem is that when I press save and play the game doesn't launch with the mod manager. Rebooting the pc doesn't fix it.

**Comment by thesupersonic16** [comment]
Did you make sure the game is not running?

**Comment by Zelop11** [comment]
Yes, when I press play in the mod loader the game start running but doesn't open. In steam it says it's running but after a few seconds it stops itself.

**Comment by thesupersonic16** [comment]
Does HMM fail to save the db without starting the game? You can check by making sure the game is closed and just pressing `Save` not `Save & Play` or `Play`.

**Comment by Zelop11** [comment]
No, that's not the problem. Can i send you a video?

**Comment by GeekCritique** [comment]
I've always had the same issue. Lost World and Forces work fine, Generations never has. Just to check, I did a fresh install on a separate drive, and got rid of all mods and SonicGMI files. No dice. The game simply refuses to boot, through HMM or through Steam, as long as "Generations Code Loader" is installed.

However, if I install CPKREDIR myself, and do _not_ have HMM's Mod Loader running, then the game runs and mods seem to work.

**Comment by Sajidur78** [comment]
@GeekCritique Have you tried loading generations without any mods or codes enabled with Generations Code Loader installed?

**Comment by GeekCritique** [comment]
@Sajidur78 I have! Still the same story. "Starting Sonic Generations" appears in the corner, but the game never actually starts.

It also fails to start if I try to run it through Steam with the Code Loader installed. In either case, there's no error message, nothing appears to load, nothing happens. The PLAY button in the Steam interface just changes to STOP for a second or two, then back to PLAY.

**Comment by thesupersonic16** [comment]
Since its the game that's failing to start, can you navigate to `%localappdata%\CrashDumps\` and just delete all the files in there and start the game once and see if a file shows up there.

**Comment by GeekCritique** [comment]
There were already a number of files related to Generations in there. I deleted them all, and you were right, when I launched the game another one showed up: "SonicGenerations.exe.8008.dmp." I don't know if you need this or not, but I've attached it just in case.

[SonicGenerations.exe.8008.zip](https://github.com/thesupersonic16/HedgeModManager/files/4615104/SonicGenerations.exe.8008.zip)

**Comment by Sajidur78** [comment]
From the crash dump it looks like its crashing when reading the cpkredir.ini file. Could you upload that file? its next to SonicGenerations.exe.

**Comment by GeekCritique** [comment]
You've got it! And thank you for helping me. :)

[cpkredir.zip](https://github.com/thesupersonic16/HedgeModManager/files/4615201/cpkredir.zip)

**Comment by Sajidur78** [comment]
@GeekCritique Could you try this version of GCL and see if the issue is still there?

[SonicGenerationsCodeLoader.zip](https://github.com/thesupersonic16/HedgeModManager/files/4615440/SonicGenerationsCodeLoader.zip)

**Comment by GeekCritique** [comment]
@Sajidur78 That seems to work, thank you!

**Comment by Sajidur78** [comment]
@GeekCritique Thanks for testing! I have submitted the changes and the fix should be live, now we just need to do something about @Zelop11's issue.

**Comment by thesupersonic16** [comment]
It's likely that the OP also had the same issue but we will need a reply to be sure.
