### ISSUE TITLE
[MetalGearRising]  error 225

### ISSUE THREAD

**Issue by AmogusEnjoyer69** [thesupersonic16/HedgeModManager#775]
HMM Info:
```
    Version: 7.10-3-3e5788b
    Args: 
    StartDir: C:\Users\90545\Desktop\Steam-UwU\steamapps\common\METAL GEAR RISING REVENGEANCE
    Process Level: User
    Game: METAL GEAR RISING: REVENGEANCE
    GameInstall: METAL GEAR RISING: REVENGEANCE
    Update Status: Up To Date
```

Exception:
```
    Type: IOException
    Message: Operation did not complete successfully because the file contains a virus or potentially unwanted software
[HMM_Snapshot_00112023104832.txt](https://github.com/thesupersonic16/HedgeModManager/files/13258911/HMM_Snapshot_00112023104832.txt)


    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
       at HedgeModManager.ModsDB.InstallModDirectory(String path, String root) in D:\a\RisingModManager\RisingModManager\HedgeModManager\ModsDB.cs:line 457
       at HedgeModManager.ModsDB.InstallMod(String path, String root) in D:\a\RisingModManager\RisingModManager\HedgeModManager\ModsDB.cs:line 306
       at HedgeModManager.MainWindow.UI_Install_Mod(Object sender, RoutedEventArgs e) in D:\a\RisingModManager\RisingModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1381
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.Controls.Primitives.ButtonBase.OnClick()
       at System.Windows.Controls.Button.OnClick()
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at HedgeModManager.HedgeApp.Main(String[] args) in D:\a\RisingModManager\RisingModManager\HedgeModManager\HedgeApp.xaml.cs:line 274
```

**Comment by hyperbx** [comment]
Rising Mod Manager is a fork of Hedge Mod Manager, please direct issues related to that [here](https://github.com/RevOcelotMGS/RisingModManager/issues).
