### ISSUE TITLE
HedgeMogManager Error [SonicGenerations] 

### ISSUE THREAD

**Issue by ghost** [thesupersonic16/HedgeModManager#792]
Please help, Mod Loader doesn't work

[HMM_Snapshot_00122023235111.txt](https://github.com/thesupersonic16/HedgeModManager/files/13533288/HMM_Snapshot_00122023235111.txt)

![image](https://github.com/thesupersonic16/HedgeModManager/assets/152672008/c44a0e42-4883-4495-a3e1-bd09c9b1b08f)

HMM Info:
```
    Version: 7.12-4
    Args: 
    StartDir: C:\Users\Cucho\Desktop\Musicas, Imagenes y juegos\Juegos y emuladores\Sonic Generations\
    Process Level: Administrator
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: IOException
    Message: The process cannot access the file 'C:\Users\Cucho\Desktop\Musicas, Imagenes y juegos\Juegos y emuladores\Sonic Generations\cpkredir.ini' because it is being used by another process.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 b

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam.

Closing.
