### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by fazelfarrokhi20** [thesupersonic16/HedgeModManager#794]
HMM Info:
```
    Version: 7.12-4
    Args: 
    StartDir: E:\Games\Young And Teenage Games\SONIC GENERATIONS 2011\Sonic Generations\
    Process Level: Administrator
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: InvalidOperationException
    Message: Cannot start process because a file name has not been provided.
    Source: System
    Function: Boolean Start()
    StackTrace: 
       at System.Diagnostics.Process.Start()
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 754
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1115
```

[HMM_Snapshot_00122023193223.txt](https://github.com/thesupersonic16/HedgeModManager/files/13548642/HMM_Snapshot_00122023193223.txt)

**Comment by fazelfarrokhi20** [comment]
please help

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam.

Closing.
