### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by GreatLuigiLV** [thesupersonic16/HedgeModManager#796]
It just crashed on boot up..

[HMM_Snapshot_00122023152534.txt](https://github.com/thesupersonic16/HedgeModManager/files/13591238/HMM_Snapshot_00122023152534.txt)

HMM Info:
```
    Version: 7.12-4
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.InternalGetDirectoryName(String path)
       at HedgeModManager.HedgeApp.FindAndSetLocalGame() in D:\GitHub\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 342
       at HedgeModManager.HedgeApp.Main(String[] args) in D:\GitHub\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 233
```

**Comment by thesupersonic16** [comment]
Your `cpkredir.ini` configuration is corrupted. The path to your mods database is pointing at the wrong place, it should be pointing to your `ModsDb.ini` file. Your configuration is pointing to a shortcut to an unrelated game.

To reset it, delete the `cpkredir.ini` file.
