### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by Maximilia00** [thesupersonic16/HedgeModManager#806]
HMM Info:
```
    Version: 7.12-4
    Args: 
    StartDir: E:\SteamLibrary\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: IOException
    Message: The process cannot access the file 'E:\SteamLibrary\steamapps\common\SonicFrontiers\Mods\Codes.dll' because it is being used by another process.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__39.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\ModsDB.cs:line 254
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__43.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 739
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1104
```

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.

**Comment by thesupersonic16** [comment]
Are you still getting the issue?
