### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by IHLIHGHIG** [thesupersonic16/HedgeModManager#809]
HMM Info:
```
    Version: 7.12-4
    Args: 
    StartDir: D:\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: InvalidOperationException
    Message: Cannot start process because a file name has not been provided.
    Source: System
    Function: Boolean Start()
    StackTrace: 
       at System.Diagnostics.Process.Start()
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 754
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1115
```

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Generations. Please install the game normally using Steam.

Closing.
