### ISSUE TITLE
[Sonic Generations] can't download anything using 1-Click button atm

### ISSUE THREAD

**Issue by rottenmind96** [thesupersonic16/HedgeModManager#81]
HMM Info:
```
    Version: 7.0-7
    Args: -gb hedgemmgens:https://gamebanana.com/mmdl/454322,Gui,35344
    StartDir: E:\Steam Games\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: WebException
    Message: The operation has timed out
    Source: System
    Function: System.Net.WebResponse GetResponse()
    StackTrace: 
       at System.Net.HttpWebRequest.GetResponse()
       at HedgeModManager.UI.GBModWindow.Download_Click(Object sender, RoutedEventArgs e)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.Controls.Primitives.ButtonBase.OnClick()
       at System.Windows.Controls.Button.OnClick()
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Window.ShowHelper(Object booleanBox)
       at System.Windows.Window.ShowDialog()
       at GameBananaAPI.GBAPI.ParseCommandLine(String line)
       at HedgeModManager.App.Main(String[] args)
    InnerException: 
```

**Comment by Sajidur78** [comment]
Seems like this was a temporary gamebanana server bug. Can you try 1-click install again and see if it works?

**Comment by rottenmind96** [comment]
Looks like it works now, but bc I ran both my browser and HMM as administrator. Not sure if it will still work with admin privileges off.

**Comment by Sajidur78** [comment]
Let me know if it crashes without admin privileges

**Comment by thesupersonic16** [comment]
It's actually not safe for both to be running as admin. I recommend dropping them back to your user and only manually elevate them when needed.

**Comment by rottenmind96** [comment]
It worked now. Yeah it was really server side issue, but that issue took a bit long so it worried me a bit.
