### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by TheBurdix** [thesupersonic16/HedgeModManager#817]
[HMM_Snapshot_00012024181137.txt](https://github.com/thesupersonic16/HedgeModManager/files/13824287/HMM_Snapshot_00012024181137.txt)

HMM Info:
```
    Version: 7.12-4
    Args: 
    StartDir: E:\SteamLibrary\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.InternalGetDirectoryName(String path)
       at HedgeModManager.HedgeApp.FindAndSetLocalGame() in D:\GitHub\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 342
       at HedgeModManager.HedgeApp.Main(String[] args) in D:\GitHub\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 233
```

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.

**Comment by thesupersonic16** [comment]
Please uninstall SonicGMI and delete cpkredir.ini

Issue appears to be the user accidentally setting the ModsDB path to a folder which not only does not exist, also is not a ModsDB file.
