### ISSUE TITLE
[SonicForces] 

### ISSUE THREAD

**Issue by superfirejack** [thesupersonic16/HedgeModManager#819]
HMM Info:
```
    Version: 7.12-4
    Args: 
    StartDir: D:\Juegos\Sonic Forces\build\main\projects\exec\
    Process Level: Administrator
    Game: Sonic Forces
    GameInstall: Sonic Forces
    Update Status: Up To Date
```

Exception:
```
    Type: InvalidOperationException
    Message: Cannot start process because a file name has not been provided.
    Source: System
    Function: Boolean Start()
    StackTrace: 
       at System.Diagnostics.Process.Start()
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 754
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1115
```

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Forces. Please install the game normally using Steam.

Closing.
