### ISSUE TITLE
[SonicForces] 

### ISSUE THREAD

**Issue by LongSkull3739** [thesupersonic16/HedgeModManager#820]
This only happens when I turn off the option called use gamelauncher, which was off as shown in the video for Sonic Forces Overclocked

[HMM_Snapshot_00012024164941.txt](https://github.com/thesupersonic16/HedgeModManager/files/13851524/HMM_Snapshot_00012024164941.txt)

HMM Info:
```
    Version: 7.12-4
    Args: 
    StartDir: D:\Sonic Forces\Sonic Forces\build\main\projects\exec\
    Process Level: User
    Game: Sonic Forces
    GameInstall: Sonic Forces
    Update Status: Up To Date
```

Exception:
```
    Type: InvalidOperationException
    Message: Cannot start process because a file name has not been provided.
    Source: System
    Function: Boolean Start()
    StackTrace: 
       at System.Diagnostics.Process.Start()
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 754
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1115
```

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Forces. Please install the game normally using Steam.

Closing.
