### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by Amazingly8000** [thesupersonic16/HedgeModManager#835]
[HMM_Snapshot_00012024193501.txt](https://github.com/thesupersonic16/HedgeModManager/files/14118835/HMM_Snapshot_00012024193501.txt)

HMM Info:
```
    Version: 7.12-4
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: TypeInitializationException
    Message: The type initializer for 'HedgeModManager.CLI.CommandLine' threw an exception.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.CLI.CommandLine+Command] ParseArguments(System.String[])
    StackTrace: 
       at HedgeModManager.CLI.CommandLine.ParseArguments(String[] args)
       at HedgeModManager.HedgeApp.OnStartup(StartupEventArgs e) in D:\GitHub\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 290
       at System.Windows.Application.<.ctor>b__1_0(Object unused)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at HedgeModManager.HedgeApp.Main(String[] args) in D:\GitHub\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 274
    InnerException: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at HedgeModManager.CLI.CommandLine.RegisterCommands(Assembly assembly) in D:\GitHub\HedgeModManager\HedgeModManager\CLI\CommandLine.cs:line 22
   at HedgeModManager.CLI.CommandLine..cctor() in D:\GitHub\HedgeModManager\HedgeModManager\CLI\CommandLine.cs:line 18
```

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.

**Comment by thesupersonic16** [comment]
Can you try installing [.NET Framework 4.8](https://go.microsoft.com/fwlink/?linkid=2088631)?
