### ISSUE TITLE
File access crash when saving compiled codes

### ISSUE THREAD

**Issue by epicRedHot** [thesupersonic16/HedgeModManager#836]
### Please use this issue if you have encounted the following exception:
```
    Type: IOException
    Message: The requested operation cannot be performed on a file with a user-mapped section open.
```
### Below is the original post
---

Any time I click "Save" or "Save and Play", I get the below error.

[HMM_Snapshot_00012024201739.txt](https://github.com/thesupersonic16/HedgeModManager/files/14119439/HMM_Snapshot_00012024201739.txt)

HMM Info:
```
    Version: 7.12-4
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: IOException
    Message: The requested operation cannot be performed on a file with a user-mapped section open.

    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__39.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\ModsDB.cs:line 254
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__43.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 739
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1104
```

**Comment by Hunt-K** [comment]
I am having this same issue with not only Gens, but Origins and Frontiers as well.
If anyone knows how to fix this please let me know.

![image](https://github.com/thesupersonic16/HedgeModManager/assets/159595758/6817e12d-c5a1-49f2-b2a8-cdd8c1f0baf3)

**Comment by S1ayerXYZ** [comment]
try removing the codes.dll file, looks like issue i was having

**Comment by thesupersonic16** [comment]
Can you all try checking if the process is running in the background while having this issue?

**Comment by cnamani45** [comment]
I deleted hedgemodmanager and everything within the Mod file, where all the mods are typically loaded. However, I couldn't delete the Codes.dll application extension because it says the app is still open even though I deleted it from my computer and ensured it wasn't downloaded. I find it interesting and wonder if that might be a clue to the hedgemodmanager not working correctly.

![Screenshot 2024-02-23 221654](https://github.com/thesupersonic16/HedgeModManager/assets/143636210/0f0f3f81-1aef-499e-b2eb-633f1f814cf7)

**Comment by cnamani45** [comment]
I forgot to mention that I was able to have two Codes.dll application extensions by moving the first one to another location and loading in a new application extension. I couldn't delete either one because the file is open in another program, but what does that mean?

**Comment by thesupersonic16** [comment]
Can you try closing all games and HMM then try again? If it fails can you show me the list of processes you have open?

**Comment by cnamani45** [comment]
How do I do that? Is it found in Task Manager?

**Comment by thesupersonic16** [comment]
Open Task Manager and select the details tab and look for Any processes starting with Sonic or HedgeModManager.

**Comment by cnamani45** [comment]
I checked, but I don't see anything Sonic or HedgeModManager. I can understand HedgeModManager not being in the task manager since I deleted it for now, but shouldn't Sonic Frontiers be visible since that's downloaded?

**Comment by thesupersonic16** [comment]
It will only show what is open.

**Comment by cnamani45** [comment]
Oh, that makes sense. I'll try opening Sonic Frontiers, and perhaps download and run HedgeModManager as well.

**Comment by thesupersonic16** [comment]
Are you currently having the issue right now where you can't move the file?

**Comment by thesupersonic16** [comment]
Might be easier to find the process by using [Process Explorer](https://download.sysinternals.com/files/ProcessExplorer.zip).

Just download that zip and extract all the files, then open `procexp64.exe`. Once the program opens, hold Ctrl and Shift, then press F, in the search box write `Codes.dll` then press Search.

**Comment by cnamani45** [comment]
Well, just recently, I restarted my PC and was able to delete the Codes.dll application extensions. However, something interesting happened when I tried opening Sonic Frontiers on Steam. I'll post some pictures.

**Comment by cnamani45** [comment]
![Screenshot 2024-02-24 121521(0)](https://github.com/thesupersonic16/HedgeModManager/assets/143636210/9505463b-fa46-47e5-8b83-5be6c50e4c05)
![Screenshot 2024-02-24 121611(1)](https://github.com/thesupersonic16/HedgeModManager/assets/143636210/436ce4cb-5fb3-463b-9a00-443469980455)
![Screenshot 2024-02-24 121935(3)](https://github.com/thesupersonic16/HedgeModManager/assets/143636210/a77b0fe6-56cf-4ae6-80b6-cab17dc3a666)

I also noticed that I'm missing emblems on the title screen I once had. I 100% the game without mods, but the game seems to act as if I still have mods. I haven't redownloaded HedgeModManager yet.

**Comment by thesupersonic16** [comment]
Deleting Hedge Mod Manager doesn't remove the mod loaders, you need to uninstall the mod loaders using HMM.

Also can you show me your SonicFrontiers folder? The modloader shouldn't be loading twice.

**Comment by cnamani45** [comment]
![Screenshot 2024-02-24 123310(4)](https://github.com/thesupersonic16/HedgeModManager/assets/143636210/3ca3bc17-8971-49e2-b8ec-cb12e9ce99ad)

**Comment by cnamani45** [comment]
I have a lot of my mods in another file in the Downloads folder called Mods

**Comment by thesupersonic16** [comment]
Can you delete both d3d11.dll and dinput8.dll then use Hedge Mod Manager to reinstall the mod loader? Also make sure you have update checking enabled.

**Comment by cnamani45** [comment]
Sure thing. Should I also permanently delete the .dll's in the recycle bin too?

**Comment by thesupersonic16** [comment]
If you want. Hedge Mod Manager should've deleted d3d11.dll on its own, also asked to delete dinput8.dll so HMM can download a clean version from GitHub.

**Comment by cnamani45** [comment]
![Screenshot 2024-02-24 124542(6)](https://github.com/thesupersonic16/HedgeModManager/assets/143636210/bd2d901a-658c-422e-98a5-36a9a9df77d9)
![Screenshot 2024-02-24 124934(7)](https://github.com/thesupersonic16/HedgeModManager/assets/143636210/063e1fcb-fc3d-428d-a95d-81a079b05225)

I first permanently deleted the d3d11.dll and dinput8.dll application extensions, then redownloaded HedgeModManager from GitHub, opened the executable, and noticed that everything was already checked marked in settings. The pictures show the results of redownloading HedgeModManager.

**Comment by thesupersonic16** [comment]
That should be fine. Are you still having the same issues?

**Comment by cnamani45** [comment]
I've been playing the game so far with the HedgeModManager enabled, and it has been working for a while. However, the same issue started happening again when I tried to click save after downloading and enabling some codes. I have not added any mods yet, and HedgeModManager was originally working with the codes turned on, too. For some reason, it decided not to work again.
![HMM Crash](https://github.com/thesupersonic16/HedgeModManager/assets/143636210/ccde6aeb-1b19-4de1-a746-32dee484158a)
![HMM Crash 2](https://github.com/thesupersonic16/HedgeModManager/assets/143636210/e1ba6705-542e-48d6-8f08-84c63a6fc903)

**Comment by thesupersonic16** [comment]
> Might be easier to find the process by using [Process Explorer](https://download.sysinternals.com/files/ProcessExplorer.zip).
> 
> Just download that zip and extract all the files, then open `procexp64.exe`. Once the program opens, hold Ctrl and Shift, then press F, in the search box write `Codes.dll` then press Search.

Try checking with Process Explorer.

**Comment by cnamani45** [comment]
I did that, but Codes.dll wouldn't show, although I did have Codes.dll in the Mods folder in the Sonic Frontiers directory. I tried opening Codes.dll to see if it will show on Process Explorer, but I don't have anything that can properly open it.

**Comment by cnamani45** [comment]
It took a while, and it also took some different solutions that seemed to work until they didn't, but I managed to solve the issue.

**Comment by thesupersonic16** [comment]
How did you resolve this issue?

**Comment by cnamani45** [comment]
I went to the Mods directory and got all my mods, Codes.hmm, and ModsDB into one folder, thus having only one folder within the main Mods directory. I left Codes.dll outside of the folder but still in the Mods directory. However, I checked and apparently made another Codes.dll inside the new folder I created with all my modes and stuff. The mod directory still works, though.

**Comment by Hunt-K** [comment]
Wait, so how exactly do I fix this?
Cause I thought all of those were in one folder already.

**Comment by thesupersonic16** [comment]
Are you able to get it to occur very consistently? If it's consistent, can you run through the [list of releases](https://github.com/thesupersonic16/HedgeModManager/releases) from top to bottom until you get a release where the issue is totally gone? Just make sure to reboot or log off and back on with every release you test.

**Comment by Hunt-K** [comment]
So just keep using different versions of the Mod Manager until it works?

**Comment by thesupersonic16** [comment]
> So just keep using different versions of the Mod Manager until it works?

Yes, but also do a reboot or log off so the issue clears when you start testing a release. Once you find a release that never has the issue, let me know so I can see what was changed.

**Comment by thesupersonic16** [comment]
I would stop at 7.10-1 if the issue continues occur to that point as it may be something else like the modloaders, which we will look into if we need to.

**Comment by Hunt-K** [comment]
I downloaded 10, 11, & 12
Still the same error.

**Comment by Hunt-K** [comment]
No matter what I do or what game I play it will give me this 
![image](https://github.com/thesupersonic16/HedgeModManager/assets/159595758/da267783-9efc-42c3-a1a2-2e2fede3c4d5)

**Comment by thesupersonic16** [comment]
> I downloaded 10, 11, & 12 Still the same error.

Got some questions:
Have you tried it after a reboot/log off? If not then we may need to look into the mod loaders.
Did it work for the first time then fail the next?
Does it happen when you press Save without ever starting any game since the last user login?

**Comment by Hunt-K** [comment]
> > I downloaded 10, 11, & 12 Still the same error.
> 
> Got some questions: Have you tried it after a reboot/log off? If not then we may need to look into the mod loaders. Did it work for the first time then fail the next? Does it happen when you press Save without ever starting any game since the last user login?

I rebooted my PC everytime I downloaded and used the versions of HedgeMod
And it happens anytime I hit Save or Save & Play, haven't been able to play since

**Comment by thesupersonic16** [comment]
So it can happen without ever touching Play or Save & Play? If so this can't be a modloader issue.

Does it also happen on the [dev version](https://nightly.link/thesupersonic16/HedgeModManager/workflows/build/rewrite/HedgeModManager-Release.zip)?

**Comment by Hunt-K** [comment]
Just downloaded it and yes.

**Comment by Hunt-K** [comment]
It's weird, I can still play the game if I load it up via Steam or click on the Shortcut
But once I try to with the Mod Loader, it throws a hissy fit

**Comment by epicRedHot** [comment]
I forgot I already made this when I posted [this other bug report](https://github.com/thesupersonic16/HedgeModManager/issues/861) a few minutes ago, my apologies. As for this -

> Can you all try checking if the process is running in the background while having this issue?

I don't see anything in Task Manager listed under "background processes" that appear to be related to Generations or HMM.

**Comment by thesupersonic16** [comment]
> I forgot I already made this when I posted [this other bug report](https://github.com/thesupersonic16/HedgeModManager/issues/861) a few minutes ago, my apologies. As for this -
> 
> > Can you all try checking if the process is running in the background while having this issue?
> 
> I don't see anything in Task Manager listed under "background processes" that appear to be related to Generations or HMM.

Can you try checking in Process Explorer as mentioned below?

> Might be easier to find the process by using [Process Explorer](https://download.sysinternals.com/files/ProcessExplorer.zip).
> 
> Just download that zip and extract all the files, then open `procexp64.exe`. Once the program opens, hold Ctrl and Shift, then press F, in the search box write `Codes.dll` then press Search.

**Comment by epicRedHot** [comment]
I was able to boot up the game a single time with HMM after restarting my computer, but after that point both Save and Save And Play went back to giving the same results as before.

I installed Process Explorer and tried searching for Codes.dll both after closing HMM and while the program was still open, but it said that there were 0 matching items during both searches.

**Comment by cnamani45** [comment]
I've been playing Sonic Frontiers for a while with the solution I found to the problem, but I later found out it was no more than a band-aid than an actual solution to the problem. I think there might be some weird bug or another problem with Codes.dll. Whenever I get the Hedgemodmanager Exception message, I would either delete or move Codes.dll outside the Mods file. This would allow me to save and play with my mods and codes, but it will create a new Codes.dll file. After some playing, closing, and playing again of the game, the Exception message would randomly decide to show up again when I try to save and play with my mods. I have to repeat the previous process to play with my mods again. 
  Also, I tried deleting all the Codes.dll files I had to move, and I could delete all of them except for one, which was the very first Codes.dll file I had before anything happened. I tried deleting it, but it said it couldn't be deleted because the Hedgemodmanager program was still open. I closed it, but I still got the same message, so I checked Task Manager and Process Explorer, but I didn't get anything that pertained to Hedgemodmanager. I still got the same message, so I deleted Hedgemodmanager again to see if the changes anything, but it didn't. I know if I restart my PC and delete the Codes.dll file again, it will work, but I've been doing that a lot recently whenever such an issue occurs. I feel like there's got to be a better way to permanently deal with the issue.
  Overall, my method did not really work all too well, but it did allow me to play with my mods for some time. 


![Screenshot 2024-03-21 065433](https://github.com/thesupersonic16/HedgeModManager/assets/143636210/2018cc23-7d6c-4e7f-928b-2ab85c854e14)
![Screenshot 2024-03-21 062537](https://github.com/thesupersonic16/HedgeModManager/assets/143636210/b86b5f72-431c-41ce-bba1-6e1fae8925e3)
![Screenshot 2024-03-21 062511](https://github.com/thesupersonic16/HedgeModManager/assets/143636210/04a22300-b209-4426-a27b-28b22906ca44)
![Screenshot 2024-03-21 060159](https://github.com/thesupersonic16/HedgeModManager/assets/143636210/65092737-2541-487f-8861-a181c20c8f89)
