### ISSUE TITLE
HMM doesnt save my mods anymore, tested on all the games i have

### ISSUE THREAD

**Issue by S1ayerXYZ** [thesupersonic16/HedgeModManager#850]
HMM doesnt save anymore, only works once after restarting computer so i am locked out of modded sonic games in general

HMM Info:
    Version: 7.12-4-0f2695f
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers

Exception:
    Type: IOException
    Message: The requested operation cannot be performed on a file with a user-mapped section open.

    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__39.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\ModsDB.cs:line 254
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__43.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 743
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1108

[HMM_Snapshot_00022024003445.txt](https://github.com/thesupersonic16/HedgeModManager/files/14231487/HMM_Snapshot_00022024003445.txt)

**Comment by S1ayerXYZ** [comment]
Ok, so the mods DO save, it just throws an error every time. i cant launch the games through hmm anymore so i have to go through steam to launch it manually now with is kinda annoying but at least i can play the game now.

**Comment by thesupersonic16** [comment]
The HMMCodes compiler is unable to save, this can be caused by another process like the game not fully closed or an AV locking the file. Please check task manager to ensure no processes are locking it like Frontiers and whatever AV you use.

You could also try deleting the Codes.dll file manually to see if it will give a reason why.

**Comment by S1ayerXYZ** [comment]
ok, so it  was the codes.dll file, it wouldnt let me delete it even after closing hmm so i just renamed it e and it made a new codes file

**Comment by S1ayerXYZ** [comment]
It constantly breaks over and over, i have removed codes.dll over 10 times

it works for a little bit then i have to remove it again
