### ISSUE TITLE
Error reading My Music Directory [Sonic Colors Ultimate]

### ISSUE THREAD

**Issue by CRE8ONICPRODUCTIONS** [thesupersonic16/HedgeModManager#851]
I started using the manager for Sonic Colors Ultimate and it was working quite well. After I went to play the game for a third time, however, I got this error on Hedge Mod: 

" HMM Info:
```
    Version: 7.12-4
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicColorsUltimate\exec
    Process Level: User
    Game: Sonic Colours: Ultimate
    GameInstall: Sonic Colours: Ultimate
    Update Status: Up To Date
```

Exception:
```
    Type: FileNotFoundException
    Message: Error reading the C:\Users\Will\Documents\My Music directory.
    Source: System
    Function: Void StartRaisingEvents()
    StackTrace: 
       at System.IO.FileSystemWatcher.StartRaisingEvents()
       at HedgeModManager.MainWindow.SetupWatcher() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 786
       at HedgeModManager.MainWindow.ResetWatchers() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 827
       at HedgeModManager.MainWindow.<Game_Changed>d__78.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1552
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at HedgeModManager.HedgeApp.Main(String[] args) in D:\GitHub\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 274 "
```

I'd appreciate any help as I can't bare playing the game with that god-awful bloom.

Thanks.

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.

**Comment by thesupersonic16** [comment]
Please send your cpkredir.ini and ModsDB.ini file or send your HMM snapshot file.
