### ISSUE TITLE
[SonicGenerations]  crashed

### ISSUE THREAD

**Issue by IMTHECOOLEST** [thesupersonic16/HedgeModManager#866]
HMM Info:
```
    Version: 7.12-5
    Args: 
    StartDir: D:\SonicGenerations\Sonic Generations\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: Win32Exception
    Message: The operation was canceled by the user
    Source: System
    Function: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
    StackTrace: 
       at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 755
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1116
```
[HMM_Snapshot_00032024194338.txt](https://github.com/thesupersonic16/HedgeModManager/files/14748778/HMM_Snapshot_00032024194338.txt)

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Generations (2011). Please install the game normally using Steam.

Closing.
