### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by samirxsz** [thesupersonic16/HedgeModManager#867]
[HMM_Snapshot_00032024092651.txt](https://github.com/thesupersonic16/HedgeModManager/files/14789405/HMM_Snapshot_00032024092651.txt)

HMM Info:
```
    Version: 7.12-5
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: Win32Exception
    Message: Aplicativo não encontrado
    Source: System
    Function: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
    StackTrace: 
       at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 755
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1116
```

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.

**Comment by DeaTh-G** [comment]
@thesupersonic16 @Sajidur78 please provide assistance.
Stale label removed.

**Comment by thesupersonic16** [comment]
From what I can see, it is most likely having issues running the Steam URI command. Can you check if running `steam://run/71340` in the browser leads to the game starting up?
