### ISSUE TITLE
[SonicForces] 

### ISSUE THREAD

**Issue by NithyanthK** [thesupersonic16/HedgeModManager#871]
extracted sonic forces overclocked mod in the mod folder located in my sonic forces folder. the mod manager is also in the sonic forces game folder. when clicking save and play i get an error making the game not run. 

[HMM_Snapshot_00042024230300.txt](https://github.com/thesupersonic16/HedgeModManager/files/14862014/HMM_Snapshot_00042024230300.txt)

HMM Info:
```
    Version: 7.12-7
    Args: 
    StartDir: C:\Program Files\Sonic Forces\build\main\projects\exec\
    Process Level: User
    Game: Sonic Forces
    GameInstall: Sonic Forces
    Update Status: Up To Date
```

Exception:
```
    Type: InvalidOperationException
    Message: Cannot start process because a file name has not been provided.
    Source: System
    Function: Boolean Start()
    StackTrace: 
       at System.Diagnostics.Process.Start()
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 756
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1117
```

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Forces. Please install the game normally using Steam.

Closing.
