### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by Paulnou** [thesupersonic16/HedgeModManager#881]
HMM Info:
```
    Version: 7.12-8
    Args: 
    StartDir: D:\SteamLibrary\steamapps\downloading\1237320\
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: DirectoryNotFoundException
    Message: Could not find a part of the path 'D:\SteamLibrary\steamapps\downloading\1237320\Mods\ModsDB.ini'.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.ModsDB.<SaveDB>d__39.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__43.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 741
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1106
```
[HMM_Snapshot_00042024193632.txt](https://github.com/thesupersonic16/HedgeModManager/files/15133732/HMM_Snapshot_00042024193632.txt)

**Comment by Sajidur78** [comment]
Maybe wait for the game to finish downloading before trying to play it with mods
