### ISSUE TITLE
[SonicOrigins] 

### ISSUE THREAD

**Issue by okl225** [thesupersonic16/HedgeModManager#882]
HMM Info:
```
    Version: 7.12-8
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SonicOrigins\build\main\projects\exec
    Process Level: User
    Game: Sonic Origins
    GameInstall: Sonic Origins
    Update Status: Up To Date
```

Exception:
```
    Type: Win32Exception
    Message: Odmowa dostępu
    Source: System
    Function: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
    StackTrace: 
       at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 756
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1117
```

**Comment by thesupersonic16** [comment]
Are you still able to reproduce this same issue?
