### ISSUE TITLE
how to fix it?

### ISSUE THREAD

**Issue by vanyalol** [thesupersonic16/HedgeModManager#887]
HMM Info:
```
    Version: 7.12-8
    Args: 
    StartDir: D:\Games\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: InvalidOperationException
    Message: Cannot start process because a file name has not been provided.
    Source: System
    Function: Boolean Start()
    StackTrace: 
       at System.Diagnostics.Process.Start()
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 756
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1117
```

**Comment by RagdollClash** [comment]
We do not support non-Steam/pirated versions of Sonic Generations (2011). Please install the game normally using Steam.

Closing.
