### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by Crazeye** [thesupersonic16/HedgeModManager#892]
HMM Info:
```
    Version: 7.12-8
    Args: 
    StartDir: G:\Steam\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.InternalGetDirectoryName(String path)
       at HedgeModManager.HedgeApp.FindAndSetLocalGame() in D:\GitHub\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 335
       at HedgeModManager.HedgeApp.Main(String[] args) in D:\GitHub\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 223
```

**Comment by thesupersonic16** [comment]
Please attach your snapshot txt file or cpkredir.ini file.
