### ISSUE TITLE
[SonicForces] 

### ISSUE THREAD

**Issue by CraftVV11** [thesupersonic16/HedgeModManager#894]
[HMM_Snapshot_00062024161229.txt](https://github.com/user-attachments/files/15881286/HMM_Snapshot_00062024161229.txt)

HMM Info:
```
    Version: 7.12-8
    Args: 
    StartDir: D:\GAMES\SteamLibrary\steamapps\common\SonicForces\build\main\projects\exec
    Process Level: User
    Game: Sonic Forces
[HMM_Snapshot_00062024161229.txt](https://github.com/user-attachments/files/15881271/HMM_Snapshot_00062024161229.txt)

    GameInstall: Sonic Forces
    Update Status: Up To Date
```

Exception:
```
    Type: FileNotFoundException
    Message: Could not load file or assembly 'System.ObjectModel, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    Source: GongSolutions.WPF.DragDrop
    Function: System.Windows.Data.CollectionViewGroup FindGroup(System.Windows.Controls.ItemsControl, System.Windows.Point)
    StackTrace: 
       at GongSolutions.Wpf.DragDrop.Utilities.ItemsControlExtensions.FindGroup(ItemsControl itemsControl, Point position)
       at GongSolutions.Wpf.DragDrop.DragInfo.InitializeDragInfo(Object sender, Object originalSource, Func`2 getPosition)
       at GongSolutions.Wpf.DragDrop.DragInfo..ctor(Object sender, MouseButtonEventArgs e)
       at GongSolutions.Wpf.DragDrop.DragDrop.DoMouseButtonDown(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnPreviewMouseDownThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at HedgeModManager.HedgeApp.Main(String[] args) in D:\GitHub\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 252
```

**Comment by thesupersonic16** [comment]
Can you try installing [.NET Framework 4.8](https://go.microsoft.com/fwlink/?linkid=2088631)?

**Comment by CraftVV11** [comment]
> Can you try installing [.NET Framework 4.8](https://go.microsoft.com/fwlink/?linkid=2088631)?

It was already installed on my computer, what else could I do?

**Comment by CraftVV11** [comment]
Hey I have activated the .NET Framework 4.8 and now it is saying that is could not load file system.Objectmodel Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    Source: GongSolutions.WPF.DragDrop

Please let me know if you have any other ideas and thank you in advance.

**Comment by thesupersonic16** [comment]
I will need @Sajidur78 to take a look at this issue as it's released to the feature he added.
