### ISSUE TITLE
Hedgemodmanager on steam deck 

### ISSUE THREAD

**Issue by Havic117** [thesupersonic16/HedgeModManager#906]
HMM Info:
```
    Version: 7.12-9
    Args: 
    StartDir: Z:\home\deck\.local\share\Steam\steamapps\common\SonicFrontiers
    Process Level: Administrator
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: IOException
    Message: File already exists.

    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
       at HedgeModManager.Linux.LinkRuntimeToProtonPrefix(Game game) in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\Linux.cs:line 152
       at HedgeModManager.MainWindow.<SaveConfig>d__55.MoveNext() in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1115
```

**Comment by RagdollClash** [comment]
Linux/Steam Deck issues should go in the pinned issue.

https://github.com/thesupersonic16/HedgeModManager/issues/219
