### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by M3SS1N** [thesupersonic16/HedgeModManager#917]
Changed the mods directory to my hard drive while on Sonic Colors Ultimate. Re-opened HMM and got this error message. No way to reset defaults or edit the directory without this crash message so I'm locked out of colors lol oops.

HMM Info:
```
    Version: 7.12-9
    Args: 
    StartDir: D:\SteamLibrary\steamapps\common\SonicColorsUltimate\exec
    Process Level: User
    Game: Sonic Colours: Ultimate
    GameInstall: Sonic Colours: Ultimate
    Update Status: Up To Date
```

Exception:
```
    Type: FileNotFoundException
    Message: Error reading the D:\System Volume Information directory.
    Source: System
    Function: Void StartRaisingEvents()
    StackTrace: 
       at System.IO.FileSystemWatcher.StartRaisingEvents()
       at HedgeModManager.MainWindow.SetupWatcher() in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 788
       at HedgeModManager.MainWindow.ResetWatchers() in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 829
       at HedgeModManager.MainWindow.<Game_Changed>d__78.MoveNext() in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1526
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at HedgeModManager.HedgeApp.Main(String[] args) in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 252
```

**Comment by thesupersonic16** [comment]
Should've added some kind of permission check. Just delete cpkredir.ini file from the exec file to reset the config.

**Comment by M3SS1N** [comment]
Okay. How exactly would I find that file? I tried looking at the .exe through a resource editor, but I couldn't find it. I also scavenged  my pc files but all I could find was the folder with the network config file in AppData. Sorry for the inconvenience!

**Comment by thesupersonic16** [comment]
The folde rpath is in the report `D:\SteamLibrary\steamapps\common\SonicColorsUltimate\exec`.

In there delete cpkredir.ini then restart HMM.

**Comment by M3SS1N** [comment]
Okay that worked! Thanks!
