### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by Degen-Again** [thesupersonic16/HedgeModManager#92]
HMM Info:
```
    Version: 7.0-7
    Args: 
    StartDir: C:\Program Files\Sega\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: UnauthorizedAccessException
    Message: Access to the path 'C:\Program Files\Sega\Sonic Generations\cpkredir.dll' is denied.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
       at HedgeModManager.App.Main(String[] args)
    InnerException: 
```

**Comment by thesupersonic16** [comment]
1. You should update HMM to this [Release on GitHub](https://github.com/thesupersonic16/HedgeModManager/releases/download/7.1-3/HedgeModManager.zip), GameBanana releases are currently out of date.

2. Try install the game using Steam.

Let me know how it went.
