### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by ChronoSMP** [thesupersonic16/HedgeModManager#96]
HMM Info:
    Version: 7.0-4
    Args: 
    StartDir: C:\Users\freak\Downloads\SonicGenerations1\Sonic Generations\Sonic Generations\
    Process Level: User
    Game: Unnamed Game

Exception:
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.Combine(String path1, String path2)
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.App.Main(String[] args)
    InnerException:

**Comment by RagdollClash** [comment]
Superseded by #97
