### ISSUE TITLE
[Bug] [Linux] Some sort of exception gets thrown when I hit save and play

### ISSUE THREAD

**Issue by DizzyDaisy909** [thesupersonic16/HedgeModManager#968]
## Describe the issue/bug

I got thrown this exception when I hit save and play after adding some mods.

HMM Info:
```
    Version: 7.13-1
    Args: 
    StartDir: Z:\var\mnt\4c9fd4e8-f325-4b9e-bf6c-5eea494603aa\SteamLibrary\steamapps\common\Sonic Hedge Mod Manager\
    Process Level: Administrator
    GameInstall: Sonic Generations (2011)
    Update Status: Up To Date
```

Exception:
```
    Type: ArgumentNullException
    Message: Value cannot be null.
Parameter name: path1
    Source: mscorlib
    Function: System.String Combine(System.String, System.String)
    StackTrace: 
       at System.IO.Path.Combine(String path1, String path2)
       at HedgeModManager.Linux.PatchRegistry(Game game) in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\Linux.cs:line 48
       at HedgeModManager.MainWindow.<SaveConfig>d__56.MoveNext() in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1139
```

## Expected Behaviour

The settings should save, and I should be able to start Sonic Generations with the mods I've selected.

## Additional Context

I'm using Fedora Silverblue 40, and the latest versions of Bottles, HedgeModManager, and Steam. SonicGMI is not installed. My system is fully updated, and exceeds the minimum requirements for Sonic Generations as well as the mod I was trying to use, the Unleashed Project.

**Comment by thesupersonic16** [comment]
Do you have a `.steam` directory in your home directory and is Bottles given permission to it?

**Comment by DizzyDaisy909** [comment]
> Do you have a `.steam` directory in your home directory and is Bottles given permission to it?

It's not in my home directory, I dug around and found it in `~/.var/app/com.valvesoftware.Steam/.steam` .
![Screenshot from 2024-11-17 19-40-58](https://github.com/user-attachments/assets/e7ab6fc1-d159-4b3f-bff3-26a696849be1)

After adding it as a directory with Flatseal, the problem persisted.
![Screenshot from 2024-11-17 19-45-58](https://github.com/user-attachments/assets/75116f0a-08ac-4c42-ac46-b2338f467e69)
[Screencast from 2024-11-17 19-47-32.webm](https://github.com/user-attachments/assets/304fa12c-a482-40c4-9d79-27d69ddbf4d8)

It also opens a second window in the top left that I can't move, as seen in the video.

**Comment by thesupersonic16** [comment]
Right now HMM only works with a normal Steam install. Could you try adding a symbolic link to `~/.steam` targetting your `~/.var/app/com.valvesoftware.Steam/.steam` and see if HMM works as expected? If it works I could try having HMM look for the path.

As for HMM opening another window, I have never seen this happen before.

**Comment by DizzyDaisy909** [comment]
Doesn't seem to work.

![Screenshot from 2024-11-17 20-42-47](https://github.com/user-attachments/assets/7edbc2b1-d280-4ae3-8818-4aafc36c4064)
![Screenshot from 2024-11-17 20-43-02](https://github.com/user-attachments/assets/be139be4-5d3a-46db-a540-9b32533f9444)
[Screencast from 2024-11-17 20-43-43.webm](https://github.com/user-attachments/assets/8c7816ab-ab75-47b7-a76f-f7a91abac708)


I'd try the normal Steam install but Silverblue only lets me use Flatpak, AppImage, and anything from their store. It's idiot-proofed to a fault, it seems.

**Comment by thesupersonic16** [comment]
I will have to make a custom build later, could be HMM not following links.

**Comment by DizzyDaisy909** [comment]
It could be that... sorry about this, and thank you for thinking about a custom build.

**Comment by thesupersonic16** [comment]
Remove the symlink you just made and then try this build.
[HedgeModManager.zip](https://github.com/user-attachments/files/17795336/HedgeModManager.zip)

**Comment by DizzyDaisy909** [comment]
Same result sadly.

**Comment by thesupersonic16** [comment]
When you installed HMM did it automatically detect all your Steam games, or did you manually add them?

**Comment by DizzyDaisy909** [comment]
I had to manually add them.

**Comment by thesupersonic16** [comment]
Give this a try.
[HedgeModManager.zip](https://github.com/user-attachments/files/17811536/HedgeModManager.zip)

**Comment by DizzyDaisy909** [comment]
Same issue sadly. 
[Screencast from 2024-11-19 08-01-58.webm](https://github.com/user-attachments/assets/eb3ec718-661b-42ee-9335-8548eabe1e2b)

**Comment by DizzyDaisy909** [comment]
Hang on! It works in Lutris. I was able to save my mod layout properly and without issue. It stopped recognizing where I installed Generations so I'm gonna reinstall it properly and report back what happens.

**Comment by DizzyDaisy909** [comment]
It works!! What I did in Lutris was just add the EXE with the default settings.
https://youtu.be/ydiO8i-N18s 
(video was too large for inline)

**Comment by thesupersonic16** [comment]
Maybe there was permission issues set for Bottles. Which exe did you use with Lutris? Could you check all the ones sent here including the latest exe from the GitHub release?

**Comment by DizzyDaisy909** [comment]
The latest one on the Releases as well as the two posted here work fine in Lutris and don't work in Bottles. They have the same permissions according to Flatseal.
![Screenshot from 2024-11-19 18-51-26](https://github.com/user-attachments/assets/760823a8-e5fa-414f-b289-0c500e2286b0)
![Screenshot from 2024-11-19 18-51-20](https://github.com/user-attachments/assets/d345f840-a299-4f12-ab29-e626c9225783)
![Screenshot from 2024-11-19 18-51-06](https://github.com/user-attachments/assets/7769058d-3b49-41aa-991a-94d8d2f92b8d)
![Screenshot from 2024-11-19 18-50-40](https://github.com/user-attachments/assets/99e546d0-7956-4329-b43a-5a4edb523cb1)

Both use the default permissions other than the extra folders Lutris needs.

**Comment by thesupersonic16** [comment]
Interesting how Lutris works. Does Lutris automatically install .NET on its own? Also not sure how the release HMM was able to work since you are using the flatpak version of Steam. Maybe it is creating its own symlink.

**Comment by DizzyDaisy909** [comment]
Sorry for not seeing this. Yeah, Lutris installs .NET on its' own. I'm just as in the dark as you are though about how this is working. I'd examine further if I knew how to do that.

**Comment by DizzyDaisy909** [comment]
Update! The 2nd modified version works better than the normal exe. Both work but the unmodified one works maybe 75% of the time. Dunno what that's about but that's what's happening. That 25% of the time, it throws the same mscorlib exception as before.
