### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by ChronoSMP** [thesupersonic16/HedgeModManager#97]
HMM Info:
```
    Version: 7.1-4
    Args: 
    StartDir: C:\Users\freak\Downloads\SonicGenerations1\Sonic Generations\Sonic Generations\HedgeModManager\
    Process Level: User
    Game: Unnamed Game
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.Combine(String path1, String path2)
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.App.Main(String[] args)
    InnerException: 
```

**Comment by RagdollClash** [comment]
Did you try placing HedgeModManager next to the Sonic Generations executable?

**Comment by thesupersonic16** [comment]
While at it you mind sending part of your libraryfolders.vdf file from your steamapps folder. I would like to see what happened to it.

I only need the part with the "X" at the start with the X being any number. (If none, Just say there's none)

Heres an example of the file. 
```json
"LibraryFolders"
{
     "TimeNextStatsReport"          "XXXXXXXX"
     "ContentStatsID"		        "XXXXXXXXXXXXXXXXX"
     "1"            "D:\\SteamLibrary"
}
```

I would need this part:
```json
     "1"            "D:\\SteamLibrary"
```
