### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by mariosbignuts** [thesupersonic16/HedgeModManager#971]
[HMM_Snapshot_00112024144533.txt](https://github.com/user-attachments/files/17930767/HMM_Snapshot_00112024144533.txt)

HMM Info:
```
    Version: 7.13-1
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\SONIC_X_SHADOW_GENERATIONS\
    Process Level: User
    GameInstall: Sonic Generations (2011)
    Update Status: Up To Date
```

Exception:
```
    Type: InvalidDataException
    Message: Found invalid data while decoding.
    Source: HedgeModManager.CodeCompiler
    Function: Void set_Body(System.String)
    StackTrace: 
       at HedgeModManager.CodeCompiler.CSharpCode.set_Body(String value)
       at HedgeModManager.CodeCompiler.CSharpCode.Parse(StreamReader reader)
       at HedgeModManager.CodeCompiler.CodeFile.Parse(Stream stream, Encoding encoding)
       at HedgeModManager.CodeCompiler.CodeFile.ParseFile(String path)
       at HedgeModManager.CodeCompiler.CodeFile.FromFiles(String[] paths)
       at HedgeModManager.MainWindow.RefreshMods() in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 292
       at HedgeModManager.MainWindow.<Window_Loaded>d__61.MoveNext() in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1292
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at HedgeModManager.HedgeApp.Main(String[] args) in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 233
```

**Comment by RostovShev03** [comment]
That can't be! Sonic Generations 2024 doesn't have proper mods support yet!

**Comment by thesupersonic16** [comment]
Not sure how HMM selected 2011 gens on SXSG.
@mariosbignuts What were you trying to do?

> That can't be! Sonic Generations 2024 doesn't have proper mods support yet!

Update on the progress of the mod loader for Sonic Generations (2024) can be found at [radfordhound.bsky.social](https://radfordhound.bsky.social)
