### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by ultim8goober** [thesupersonic16/HedgeModManager#972]
HMM Info:
```
    Version: 7.13-1
    Args: 
    StartDir: C:\Users\grant\Downloads\
    Process Level: User
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: DirectoryNotFoundException
    Message: Could not find a part of the path 'C:\Program Files (x86)\Steam\steamapps\common\SonicFrontiers\mods\ModsDB.ini'.
    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
       at HedgeModManager.ModsDB.<SaveDB>d__39.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__44.MoveNext() in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 764
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__56.MoveNext() in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1132
```

**Comment by thesupersonic16** [comment]
Where is the Sonic Frontiers game files located?
