### ISSUE TITLE
[SonicFrontiers] Openning Hedgemod manager causes it to crash immediately after clicking or interacting.

### ISSUE THREAD

**Issue by Hotdogmanpowers** [thesupersonic16/HedgeModManager#973]
This error has been going on for months now and I can't seem to figure out why, I tried uninstalling and reinstalling, I tried updating the .NET Framework to 4.8, I tried updating my own PC, and the only way I can make it work is if I reinstall the system every time I need to open it and it's becoming bothersome. This also prevents me from downloading certain mods due to "Characters being illegal", and whatnot so I have to download it manually instead. If there is any way I can fix this, please let me know.

HMM Info:
```
    Version: 7.13-1
    Args: 
    StartDir: C:\Users\15125\Downloads\
    Process Level: User
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: FileNotFoundException
    Message: Could not load file or assembly 'System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    Source: GongSolutions.WPF.DragDrop
    Function: Void InitializeDragInfo(System.Object, System.Object, System.Func`2[System.Windows.IInputElement,System.Windows.Point])
    StackTrace: 
       at GongSolutions.Wpf.DragDrop.DragInfo.InitializeDragInfo(Object sender, Object originalSource, Func`2 getPosition)
       at GongSolutions.Wpf.DragDrop.DragInfo..ctor(Object sender, MouseButtonEventArgs e)
       at GongSolutions.Wpf.DragDrop.DragDrop.DoMouseButtonDown(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnPreviewMouseDownThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at HedgeModManager.HedgeApp.Main(String[] args) in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 233
```

**Comment by MysticBlue54** [comment]
I have the same exact issue and i haven't been able to find anything on it either. Only codes work for me.

**Comment by thesupersonic16** [comment]
~~Try reinstall .NET Framework 4.8 if it allows you.~~ I can't read I guess.

I have nothing in mind that can help you. Sorry. 

Can you show me the exception for the "Characters being illegal"?
