### ISSUE TITLE
[SonicFrontiers] HMM bug with the mod list. It repeatedly crashes, both with a mod or no mods there. Help.

### ISSUE THREAD

**Issue by MysticBlue54** [thesupersonic16/HedgeModManager#978]
HMM Info:
```
    Version: 7.13-1
    Args: 
    StartDir: C:\Users\User\Downloads\
    Process Level: User
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: FileNotFoundException
    Message: Could not load file or assembly 'System.ObjectModel, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    Source: GongSolutions.WPF.DragDrop
    Function: System.Windows.Data.CollectionViewGroup FindGroup(System.Windows.Controls.ItemsControl, System.Windows.Point)
    StackTrace: 
       at GongSolutions.Wpf.DragDrop.Utilities.ItemsControlExtensions.FindGroup(ItemsControl itemsControl, Point position)
       at GongSolutions.Wpf.DragDrop.DragInfo.InitializeDragInfo(Object sender, Object originalSource, Func`2 getPosition)
       at GongSolutions.Wpf.DragDrop.DragInfo..ctor(Object sender, MouseButtonEventArgs e)
       at GongSolutions.Wpf.DragDrop.DragDrop.DoMouseButtonDown(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnPreviewMouseDownThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at HedgeModManager.HedgeApp.Main(String[] args) in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 233
```

**Comment by thesupersonic16** [comment]
Duplicate of #869. Cause and solution is currently unknown.

**Comment by thesupersonic16** [comment]
Oh actually this issue is different my bad. I still do not know the cause and solution. Maybe try install .NET Framework 4.8 if it allows you.

**Comment by lolboibye** [comment]
I am getting this error as well I would really like a fix
