### ISSUE TITLE
[SonicFrontiers] Saving Issues.

### ISSUE THREAD

**Issue by DrBrainless** [thesupersonic16/HedgeModManager#979]
I've got some problem after I tried enabling the debug console 

[HMM_Snapshot_00122024154456.txt](https://github.com/user-attachments/files/18219918/HMM_Snapshot_00122024154456.txt)

HMM Info:
```
    Version: 7.13-1
    Args: 
    StartDir: Z:\home\drbrainless\HMM\
    Process Level: Administrator
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: IOException
    Message: File already exists.

    Source: mscorlib
    Function: Void WinIOError(Int32, System.String)
    StackTrace: 
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
       at HedgeModManager.Linux.LinkRuntimeToProtonPrefix(Game game) in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\Linux.cs:line 190
       at HedgeModManager.MainWindow.<SaveConfig>d__56.MoveNext() in C:\Users\User\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 1141
```

**Comment by thesupersonic16** [comment]
All issues related to running HMM on Linux should go to #219. Closing.

To quickly answer the issue, the function to link the runtime nolonger works, try this method below, if it does not work, try asking in the issue linked above.

- Manually installing libraries from another system.
  - Download [windows.7z](https://files.gamebanana.com/bitpit/windows.7z).
  - Locate the game's prefix. Usually located in `~/.local/share/Steam/steamapps/compatdata/<GAMEID>/pfx`
  - Enter the drive_c directory of the game prefix then `windows` and delete or rename the `Microsoft.NET` directory
  - Extract archive contents into the game's `drive_c` directory

**Comment by DrBrainless** [comment]
Thanks.
