### ISSUE TITLE
[Bug] HedgeModMan crashes as soon as i try to boot up

### ISSUE THREAD

**Issue by HiroChao** [thesupersonic16/HedgeModManager#980]
## Describe the issue/bug

I don't know why but today the mod manager just decided to not work at all, I tried deleting it, reinstalling it, and all that but nothing worked
## Expected Behaviour

I expected it to work like it usually does, booting up and letting me pick my sonic game so i can mod it and play it
## Additional Context

[HMM_Snapshot_00122024154552.txt](https://github.com/user-attachments/files/18223191/HMM_Snapshot_00122024154552.txt)

**Comment by thesupersonic16** [comment]
It appears to be having issues loading classes in relation of CLI. 

Can you try this build and send the contents of the message box (You should beable to use Ctrl + C) into here?
[HedgeModManager.zip](https://github.com/user-attachments/files/18224219/HedgeModManager.zip)

**Comment by HiroChao** [comment]
it says this

HMM Info:
    Version: 7.13-1-3ec416d
    Args: 
    StartDir: E:\
    Process Level: User
    GameInstall: Sonic Frontiers

Exception:
    Type: TypeInitializationException
    Message: The type initializer for 'HedgeModManager.CLI.CommandLine' threw an exception.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.CLI.CommandLine+Command] ParseArguments(System.String[])
    StackTrace: 
       at HedgeModManager.CLI.CommandLine.ParseArguments(String[] args)
       at HedgeModManager.HedgeApp.OnStartup(StartupEventArgs e) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 249
       at System.Windows.Application.<.ctor>b__1_0(Object unused)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at HedgeModManager.HedgeApp.Main(String[] args) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 233
    InnerException: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at HedgeModManager.CLI.CommandLine.RegisterCommands(Assembly assembly) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\CLI\CommandLine.cs:line 22
   at HedgeModManager.CLI.CommandLine..cctor() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\CLI\CommandLine.cs:line 18

**Comment by thesupersonic16** [comment]
Can make sure you are using the build I sent you?

**Comment by Darksound9** [comment]
Wanted to chime in to say I have a similar issue, potentially a different bug. Happy to move this to a separate git issue if you'd prefer.

Used HMM only with Shadow Generations, had a handful of mods. Win10 PC.
The mods were still working, but this last Saturday I could no longer open HMM, any version, from any directory--including the debug version you linked above.

I tried launching thru command prompt to get debug output which only gives the following:

D:\Downloads\HedgeModManager>HedgeModManager.exe /debuglog

D:\Downloads\HedgeModManager>
Process is terminated due to StackOverflowException.

There has to be a config somewhere I need to wipe, right? I've already uninstalled the game and wiped the only mod folders for it (that I am aware of)

**Comment by thesupersonic16** [comment]
@Darksound9 Please don't delete anything right now, it is better to know the issue and prevent it in a later update over keeping it unknown.

Since you had a crash, can you check `%localappdata%\CrashDumps` for any files contaning the word `HedgeModManager`?
